// engine
import type { QuestionTranslation } from '../../engine/question';

export const translations: Record<string, QuestionTranslation> = {
  'csharp-struct-value-copy': {
    prompt:
      "```csharp\nstruct Point\n{\n    public int X;\n}\n\nvar p1 = new Point { X = 1 };\nvar p2 = p1;\np2.X = 99;\n\nConsole.WriteLine(p1.X);\n```\n¿Qué imprime esto?",
    options: {
      a: '`1`',
      b: '`99`',
      c: 'Un error de compilación, porque `p2 = p1` no puede copiar un `struct`',
      d: '`0`',
    },
    explanation:
      '`Point` es un `struct`, un **tipo por valor**. `var p2 = p1;` copia todos los campos de `p1` en una instancia nueva e independiente, así que modificar `p2.X` no afecta a `p1`. `p1.X` sigue valiendo `1`. `99` solo sería correcto si `Point` fuera una `class`: entonces `p1` y `p2` serían dos referencias al **mismo** objeto en el heap, y `p2.X = 99` también se vería a través de `p1`. La asignación compila sin problema, así que la respuesta del error de compilación es incorrecta, y `p1.X` se estableció explícitamente en `1` en el inicializador, no quedó en el valor por defecto `0`, así que la respuesta `0` también es incorrecta.',
    hint: "Pregúntate si un `struct` es un tipo por valor o por referencia, y qué hace la asignación con cada tipo.",
  },
  'csharp-async-task-vs-async-void': {
    prompt:
      'Estás escribiendo un método que realiza una operación asíncrona y necesita que quien lo llama pueda hacerle `await` y capturar cualquier excepción con un `try`/`catch` normal alrededor de la llamada. ¿Qué firma deberías usar?',
    options: {
      a: '`public async Task DoWorkAsync()`',
      b: '`public async void DoWorkAsync()`',
      c: '`public void DoWorkAsync()`, que bloquea internamente sobre el trabajo asíncrono con `.GetAwaiter().GetResult()`',
      d: '`public async Task<void> DoWorkAsync()`',
    },
    explanation:
      "Un método `async Task` devuelve un `Task` al que quien llama puede hacerle `await`; cualquier excepción lanzada dentro se captura en ese `Task` y se vuelve a lanzar en el `await`, así que un `try`/`catch` normal alrededor de la llamada la detecta. `async void` es del tipo \"dispara y olvida\": no hay ningún `Task` al que hacerle `await`, y una excepción lanzada dentro se dispara sobre el `SynchronizationContext` actual en lugar de poder ser capturada por quien llama, lo que típicamente termina tumbando el proceso. Existe principalmente para manejadores de eventos de UI, que no pueden devolver un valor. Un método `void` normal no es `async` en absoluto, así que no puede hacer `await`; bloquear con `.GetAwaiter().GetResult()` dentro de él solo vuelve síncrona la llamada y no le da a quien llama nada a lo que hacerle `await` — y si esto se ejecuta en un hilo con un `SynchronizationContext` de un solo hilo capturado (un hilo de UI, o el ASP.NET clásico), bloquear así arriesga un deadlock, porque la continuación necesita ese mismo hilo para reanudarse. `Task<void>` no es válido en C#: `void` no puede usarse como argumento de tipo, así que la firma con `Task<void>` no compila; usa `Task` para \"sin valor de retorno\" y `Task<T>` cuando necesites uno.",
    hint: "Piensa en qué necesita recibir quien llama para poder hacer `await`, y adónde va una excepción cuando no hay nada que esperar.",
  },
  'csharp-nullable-reference-warning': {
    prompt:
      "```csharp\n#nullable enable\n\npublic class UserService\n{\n    public string GetDisplayName(User? user)\n    {\n        return user.Name;\n    }\n}\n```\nCon los tipos de referencia anulables habilitados, ¿qué pasa cuando esto se compila, y qué ocurre realmente en tiempo de ejecución si se llama a `GetDisplayName(null)`?",
    options: {
      a: 'La compilación falla con el error CS8602, así que el proyecto nunca compila hasta que se corrija el código',
      b: 'El compilador emite una **advertencia** (CS8602, posible desreferencia de una referencia nula); el código igual compila. En tiempo de ejecución, `user.Name` lanza una `NullReferenceException` cuando `user` es `null` — agrega una verificación de null (o usa `user?.Name`) antes de acceder al miembro',
      c: 'El runtime lanza automáticamente `ArgumentNullException` antes de que se ejecute el cuerpo del método, porque el parámetro está anotado como `User?`',
      d: 'Los tipos de referencia anulables solo afectan a los tooltips del editor; no hay ningún diagnóstico del compilador',
    },
    explanation:
      "Los tipos de referencia anulables son una característica de **análisis de flujo en tiempo de compilación**, no un mecanismo de verificación nula en tiempo de ejecución: por defecto los diagnósticos son advertencias, no errores, así que la opción de \"el build falla con el error CS8602\" es incorrecta — el proyecto compila. Marcar el parámetro como `User?` le dice al compilador que el argumento puede ser `null`, y acceder a `.Name` sin acotarlo (un `if (user is null) return ...;`, un operador condicional nulo `user?.Name`, o un operador de indulgencia nula `user!.Name` cuando estás seguro de que no es null) dispara CS8602. Nada en la anotación cambia lo que pasa en tiempo de ejecución: pasar `null` sigue lanzando una `NullReferenceException` normal al desreferenciar, exactamente igual que en código antiguo sin soporte para anulables, así que la opción de `ArgumentNullException` es incorrecta — no se inserta ninguna verificación. Las advertencias son diagnósticos reales del compilador, visibles en la salida del build y en CI, no solo pistas del editor, así que la opción de \"solo afectan los tooltips del editor\" también es incorrecta.",
    hint: "Separa lo que revisa el compilador de lo que pasa cuando el código se ejecuta, y evalúa por separado cada mitad de cada opción.",
  },
  'csharp-task-whenall-exceptions': {
    prompt:
      "```csharp\nvar task1 = Task.Run(() => { throw new InvalidOperationException(\"A\"); });\nvar task2 = Task.Run(() => { throw new ArgumentException(\"B\"); });\n\ntry\n{\n    await Task.WhenAll(task1, task2);\n}\ncatch (Exception ex)\n{\n    Console.WriteLine(ex.GetType().Name);\n}\n```\n¿Qué se imprime, y cómo se observa la excepción de la otra tarea?",
    options: {
      a: 'Imprime `InvalidOperationException`. El `await` sobre la tarea de `WhenAll` vuelve a lanzar solo la **primera** excepción interna, y `WhenAll` conserva el orden de entrada en `Exception.InnerExceptions`, así que la excepción de `task1` queda primero. Para ver ambas, guarda una referencia a la tarea que devuelve `WhenAll` en lugar de hacerle `await` en línea: `var all = Task.WhenAll(task1, task2); try { await all; } catch { } var errores = all.Exception!.InnerExceptions;` — o lee `task1.Exception` / `task2.Exception` una vez que cada tarea termina',
      b: 'Imprime `AggregateException`, porque .NET envuelve ambas excepciones en un tipo personalizado único y lo vuelve a lanzar en el `await`',
      c: 'Imprime `ArgumentException`, porque `Task.WhenAll` siempre expone la excepción de la tarea que se pasó en **último** lugar',
      d: 'Imprime `InvalidOperationException`, porque `Task.WhenAll` cancela `task2` en el momento en que `task1` falla, así que la excepción de `task2` nunca se llega a registrar',
    },
    explanation:
      "`Task.WhenAll` termina en estado Faulted con una `AggregateException` cuyo `InnerExceptions` contiene la excepción de cada tarea que falló, en el orden en que las tareas se pasaron a `WhenAll`, no en el orden en que completaron. Cuando haces `await` sobre una tarea fallida (incluida la que devuelve `WhenAll`), el awaiter desenvuelve y vuelve a lanzar solo la **primera** excepción interna, por eso el `catch` aquí ve `InvalidOperationException` (la respuesta de `AggregateException` es incorrecta: .NET no envuelve las dos excepciones en ningún otro tipo personalizado — el `.Exception` de la tarea fallida de `WhenAll` sí es realmente una `AggregateException`, pero el `await` nunca deja que esa `AggregateException` salga tal cual en el punto de la llamada; siempre la desenvuelve hasta dejar solo la primera excepción interna). La respuesta de `ArgumentException` invierte el orden, y la de la cancelación es incorrecta porque `WhenAll` nunca cancela tareas hermanas solo porque una falle — ambas tareas terminan de ejecutarse de forma independiente, así que `task2.Exception` también queda poblada. Revisar `.Exception.InnerExceptions` sobre una referencia guardada a la tarea de `WhenAll` (o el `.Exception` de cada tarea) después del `await` es la forma estándar de ver todos los fallos en vez de solo el primero — no vuelvas a llamar a `Task.WhenAll` para intentar obtenerlos.",
    hint: "Recuerda cómo `await` desenvuelve la `AggregateException` de una tarea fallida, y en qué orden `WhenAll` registra las excepciones internas.",
  },
  'csharp-linq-first-vs-firstordefault': {
    prompt:
      "```csharp\nList<int> numbers = new List<int>();\nint result = numbers.First();\n```\n¿Qué pasa aquí, y qué deberías usar en su lugar si `numbers` puede legítimamente estar vacía?",
    options: {
      a: '`First()` lanza `InvalidOperationException` ("Sequence contains no elements"). Usa `FirstOrDefault()`, que devuelve `default(int)` (`0`) para una secuencia vacía, o la sobrecarga `FirstOrDefault(predicate, defaultValue)` para dar tu propio valor de respaldo en lugar de `0`',
      b: '`First()` devuelve silenciosamente `default(int)` (`0`), exactamente igual que `FirstOrDefault()`, así que no hay ninguna diferencia práctica entre ambos',
      c: '`First()` lanza `ArgumentOutOfRangeException`, la misma excepción que lanza `List<int>.this[int]` para un índice inválido',
      d: 'El código no compila, porque `result` tendría que declararse `int?` para poder guardar el resultado de `First()`',
    },
    explanation:
      "`First()` está pensado para secuencias que se esperan no vacías: lanza `InvalidOperationException` cuando no hay nada que devolver, así que la opción de \"devuelve `0` en silencio\" es incorrecta — eso describe el comportamiento de `FirstOrDefault()`, no el de `First()`. `ArgumentOutOfRangeException` pertenece al acceso por índice o a arrays, no al caso de secuencia vacía de LINQ. El código compila sin problema como `int`, así que la opción del error de compilación es incorrecta — simplemente lanza en tiempo de ejecución. La trampa real que hay que mencionar en una entrevista: `FirstOrDefault()` sobre una `List<int>` vacía devuelve `0`, indistinguible de un `0` real que ya estuviera en la lista, así que cuando `0` es un valor válido verifica `Any()` (o `Count == 0`) antes de llamar a `FirstOrDefault()`, o proyecta primero a un tipo anulable — `numbers.Select(n => (int?)n).FirstOrDefault()` devuelve `null` en lugar de un `0` ambiguo para una secuencia vacía. LINQ no tiene ningún método \"first\" al estilo `TryGetValue` que reporte el éxito por separado del valor.",
    hint: "Compara el contrato de `First` con el de su variante `OrDefault` cuando la secuencia no tiene nada, y cuál es el valor por defecto de `int`.",
  },
  'csharp-record-equality-with-collections': {
    prompt:
      "```csharp\npublic record Order(int Id, List<string> Items);\n\nvar a = new Order(1, new List<string> { \"pen\" });\nvar b = new Order(1, new List<string> { \"pen\" });\n\nConsole.WriteLine(a == b); // ?\n```\n¿Por qué esto imprime `False` aunque ambas órdenes tienen el mismo `Id` y los mismos artículos? ¿Qué otras trampas tiene la igualdad de `record` con miembros mutables o de tipo colección, y cómo corregirías esta?",
    modelAnswer:
      "Los records sintetizan `Equals`/`GetHashCode` miembro a miembro, comparando cada uno de los campos de instancia subyacentes del record — los campos de respaldo detrás de sus propiedades posicionales o init-only, más cualquier campo declarado explícitamente — con `EqualityComparer<T>.Default`; una propiedad calculada, con cuerpo de expresión y sin campo de respaldo, no forma parte de esa comparación en absoluto. Para `List<string>`, ese comparador por defecto termina usando `object.Equals`/`GetHashCode` — igualdad por referencia — porque `List<T>` nunca los sobrescribe. `a.Items` y `b.Items` son dos listas creadas por separado con `new`, así que aunque su contenido es igual, la comparación del campo falla y todo el record se compara como distinto, lo cual sorprende a quien espera que los records den \"igualdad de valor\" completa de fábrica. Una trampa relacionada: la igualdad de records también compara una propiedad oculta `EqualityContract` ligada al tipo en tiempo de ejecución, así que un record derivado nunca es igual a una instancia con el tipo base aunque tenga valores de propiedad idénticos, incluso sin ninguna colección de por medio. Para corregir el caso de la colección, no puedo sobrescribir `Equals(object)` directamente — el compilador no lo permite en un record — así que declaro `public virtual bool Equals(Order? other) => other is not null && Id == other.Id && Items.SequenceEqual(other.Items);` (sin `virtual` si el record es `sealed`), más un `public override int GetHashCode()` a juego, construido acumulando los elementos en vez de con `HashCode.Combine` (que solo acepta una cantidad fija de argumentos y no puede hashear una lista de longitud variable): `var hash = new HashCode(); hash.Add(Id); foreach (var item in Items) hash.Add(item); return hash.ToHashCode();`. Donde controle el diseño, también consideraría envolver la colección en un tipo pequeño con su propia implementación de `IEquatable<T>`, ya que ni siquiera las colecciones \"inmutables\" de la BCL como `ImmutableArray<T>`/`ImmutableList<T>` dan igualdad estructural gratis — igual tendría que compararlas o envolverlas explícitamente. En cualquier caso, no confío en la igualdad de record por defecto una vez que algún miembro no implemente igualdad de valor por sí mismo.",
    rubric: [
      "Explica que los records sintetizan Equals/GetHashCode miembro a miembro sobre los campos de instancia subyacentes del record usando EqualityComparer<T>.Default (no sobre propiedades calculadas arbitrarias sin campo de respaldo)",
      'Explica que List<T> no sobrescribe Equals/GetHashCode, así que esa comparación es por referencia — dos records construidos con listas distintas pero de contenido igual no son iguales, pese a la fama de igualdad de valor de los records',
      'Menciona la verificación de EqualityContract/tipo en tiempo de ejecución: un record derivado nunca es igual a una instancia con tipo base aunque los valores de propiedad sean idénticos',
      "Propone una solución concreta: declarar `public virtual bool Equals(Order? other)` (no `Equals(object)`, que no se puede sobrescribir en un record) más `public override int GetHashCode()` construido acumulando con `HashCode.Add` sobre los elementos, en lugar de asumir que un tipo de colección inmutable de la BCL da igualdad estructural gratis",
    ],
    explanation:
      "Esto se pregunta para ver si \"los records tienen igualdad de valor\" se entiende al nivel de lo que el compilador realmente genera, y no como eslogan de marketing. Es una fuente común de bugs sutiles: pruebas unitarias que comparan DTOs llenos de listas, o records usados como claves de diccionario o en `HashSet<T>`, se comportan de repente como tipos por referencia en cuanto interviene un miembro de tipo colección.\n\n**Dilo en voz alta:** \"La igualdad de records es miembro a miembro sobre los campos del record usando el comparador por defecto, y `List<T>` no tiene igualdad de valor, así que dos records construidos con instancias de lista distintas pero contenido idéntico no van a dar `==`. Si necesito eso, agrego mi propio `Equals(Order? other)` y `GetHashCode()` usando `SequenceEqual` en lugar de confiar en los sintetizados.\"",
    hint: "Piensa en qué comparador usa el `Equals` sintetizado para cada campo, si `List<T>` sobrescribe la igualdad, y qué verifica `EqualityContract`.",
  },
  'csharp-configureawait-and-valuetask': {
    prompt:
      "Mantienes una librería compartida cuyas APIs asíncronas se llaman tanto desde un servicio ASP.NET Core como desde una app de escritorio WPF. ¿Cuándo usas `ConfigureAwait(false)`, y cuándo expondrías un método como `ValueTask<T>` en lugar de `Task<T>`? ¿Cuál es el riesgo de usar `ValueTask<T>` incorrectamente?",
    modelAnswer:
      "`ConfigureAwait(false)` le dice al `await` que no intente reanudar la continuación sobre el `SynchronizationContext`/`TaskScheduler` capturado. En código de librería no controlo el contexto de quien llama, así que lo uso después de prácticamente todo `await` interno — evita el clásico deadlock donde código WPF/WinForms bloquea de forma síncrona sobre la llamada asíncrona (`.Result`, `.Wait()`) mientras retiene el `SynchronizationContext` de la UI, porque la continuación necesitaría ese mismo hilo para reanudarse. Esto solo funciona si `ConfigureAwait(false)` se aplica de forma consistente: tiene que estar en todos los `await` de la cadena por la que pasa la llamada bloqueada, no solo en el más externo, porque basta con una sola continuación capturada en cualquier punto más abajo para producir el deadlock. ASP.NET Core (Kestrel) no tiene `SynchronizationContext` por defecto desde .NET Core, así que ahí `ConfigureAwait(false)` no evita ningún deadlock, pero sigue valiendo la pena en código de librería compartida, tanto por consistencia como por el pequeño ahorro de saltarse el cambio de contexto, ya que la librería no sabe quién la va a llamar. Para `ValueTask<T>`, solo lo uso en un camino caliente que se completa de forma síncrona con mucha frecuencia — una búsqueda en caché que casi siempre acierta, por ejemplo — donde asignar un `Task<T>` en cada llamada agrega presión real sobre el GC. El problema es que `ValueTask<T>` tiene un contrato de uso mucho más estricto que `Task<T>`: hay que hacerle `await` (o convertirlo una sola vez con `AsTask()`) exactamente una vez, no se le puede hacer `await` dos veces ni de forma concurrente desde dos sitios, y no debería guardarse ni pasarse por ahí para inspeccionarlo después, porque su `IValueTaskSource` puede reutilizarse (pooling) después del primer consumo — hacer cualquiera de esas cosas produce un comportamiento indefinido o excepciones, no un error de compilación. Así que por defecto uso `Task<T>` en todas partes, y solo cambio un método específico a `ValueTask<T>` después de que el profiling muestre que las asignaciones de ese camino de completado síncrono realmente importan, manteniendo el uso local (hacerle `await` de inmediato, nunca guardar el `ValueTask` en sí).",
    rubric: [
      'Explica que ConfigureAwait(false) evita capturar/reanudar sobre el SynchronizationContext, previniendo deadlocks cuando quien llama bloquea sobre resultados asíncronos (WPF/WinForms)',
      'Señala que ASP.NET Core no tiene SynchronizationContext por defecto, así que ahí ConfigureAwait(false) es cuestión de higiene/rendimiento de librería y no de prevenir deadlocks',
      'Explica que ValueTask<T> existe para evitar una asignación de Task en caminos calientes que completan de forma síncrona con frecuencia',
      'Indica el riesgo del contrato de ValueTask: hay que hacerle await exactamente una vez y no guardarlo/consumirlo de forma concurrente, a diferencia de Task<T>, porque su fuente puede reutilizarse',
      'Recomienda Task<T> como opción por defecto, recurriendo a ValueTask<T> solo después de que el profiling muestre presión de asignaciones',
    ],
    explanation:
      "Esto evalúa si el candidato trata `ConfigureAwait(false)` y `ValueTask<T>` como algo para poner en todas partes por reflejo o como herramientas puntuales para modos de fallo y caminos calientes específicos — usar cualquiera de los dos sin entender el compromiso causa bugs reales (deadlocks por un lado, comportamiento indefinido por mal uso de `ValueTask` por el otro).\n\n**Dilo en voz alta:** \"`ConfigureAwait(false)` protege al código de librería de un deadlock causado por el `SynchronizationContext` de quien llama; `ValueTask<T>` ahorra una asignación en caminos calientes que suelen completar de forma síncrona, pero es de un solo uso, así que lo mantengo local y por defecto uso `Task<T>` en todo lo demás.\"",
    hint: "Cubre qué implica capturar el `SynchronizationContext` para quien bloquea (WPF frente a ASP.NET Core), y el contrato de consumo único de `ValueTask<T>`.",
  },
  'csharp-linq-deferred-execution-multiple-enumeration': {
    prompt:
      "```csharp\nIEnumerable<int> Squares(IEnumerable<int> source)\n{\n    Console.WriteLine(\"Building query\");\n    return source.Select(x =>\n    {\n        Console.WriteLine($\"Evaluating {x}\");\n        return x * x;\n    });\n}\n\nvar query = Squares(new[] { 1, 2, 3 });\nConsole.WriteLine(\"Before first enumeration\");\nforeach (var s in query) { }\nConsole.WriteLine(\"Before second enumeration\");\nforeach (var s in query) { }\n```\n¿Cuáles de las siguientes afirmaciones sobre este código son verdaderas? Selecciona todas las que apliquen.",
    options: {
      a: '"Building query" se imprime exactamente una vez en total, en el momento en que se llama a `Squares(...)`, antes de que se ejecute cualquiera de los dos `foreach`',
      b: '"Evaluating {x}" se imprime para cada elemento **dos veces** en total (una por cada `foreach`), porque `Select` usa ejecución diferida y `query` nunca se materializó, así que cada enumeración vuelve a ejecutar todo el pipeline sobre `source`',
      c: 'Llamar a `Squares(new[] { 1, 2, 3 })` evalúa de inmediato la proyección `Select` y guarda en caché los tres resultados, así que el segundo `foreach` reutiliza los cuadrados en caché sin volver a imprimir "Evaluating"',
      d: 'Como `source` es un array (ya completamente materializado en memoria), LINQ memoriza automáticamente los resultados de `Select` la primera vez que se enumera `query`',
      e: 'Agregar `.ToList()` justo después de `.Select(...)` dentro de `Squares` haría que "Evaluating" se imprima exactamente tres veces en total, todas mientras se ejecuta `Squares(...)` — antes de que se imprima siquiera "Before first enumeration" — y ninguno de los dos `foreach` imprimiría "Evaluating", porque ambos solo leerían la `List<int>` ya construida',
    },
    explanation:
      "`Select` (como `Where`, `OrderBy` y la mayoría de los operadores de LINQ-to-Objects) es **diferido**: no toca `source` cuando se llama, solo construye un iterador. `Console.WriteLine(\"Building query\")` se ejecuta de inmediato porque es una instrucción normal dentro de `Squares`, ejecutada una vez cuando se invoca el método mismo — antes de que exista siquiera el iterador diferido de `Select`, así que la afirmación de \"se imprime exactamente una vez\" es verdadera. Cada `foreach` sobre `query` llama a `GetEnumerator()` sobre ese mismo pipeline sin materializar, que recorre `source` y vuelve a invocar el selector desde cero, así que \"Evaluating\" se imprime para los tres elementos en el primer bucle y otra vez para los tres en el segundo — seis impresiones en total. Así que la afirmación de \"se imprime dos veces\" es verdadera, y las dos que hablan de caché son falsas — nada en `Select`, ni el hecho de que la fuente sea un array, provoca un cacheo automático. Esta es la trampa de la **enumeración múltiple**: duplica el trabajo en silencio, y es peor que un problema de rendimiento cuando la fuente tiene efectos secundarios o no se puede re-enumerar de forma segura — una consulta construida sobre `IQueryable`/EF Core vuelve a ejecutar la consulta a la base de datos, un iterador con `yield return` que depende de estado externo puede comportarse distinto la segunda vez, y una fuente de un solo sentido como un `DbDataReader` o un iterador respaldado por un `Stream` ya consumido puede lanzar una excepción o no devolver nada. Llamar a `.ToList()` (o `.ToArray()`) convierte el pipeline diferido en uno evaluado de forma anticipada: si `Squares` hiciera eso internamente justo después de `.Select(...)`, las tres impresiones de `Evaluating` ocurrirían de inmediato durante la llamada a `Squares(...)` — antes de que se imprima siquiera `\"Before first enumeration\"` — y ninguno de los dos `foreach` imprimiría `Evaluating`, porque ambos solo leerían la `List<int>` ya construida, así que la afirmación sobre `.ToList()` es verdadera. Sigue siendo la solución estándar siempre que una consulta LINQ se vaya a enumerar más de una vez — solo hay que poner el `.ToList()` donde realmente se quiere que ocurra la evaluación anticipada, sin asumir que ocurre de forma perezosa en cada enumeración.\n\n**Dilo en voz alta:** \"Los operadores de LINQ como `Select` son diferidos, así que cada enumeración vuelve a ejecutar todo el pipeline a menos que lo materialice. Si voy a enumerar una consulta más de una vez, o tiene efectos secundarios, llamo a `ToList()` una vez y reutilizo eso.\"",
    hint: "Separa lo que se ejecuta al llamar a `Squares` de lo que se ejecuta cada vez que se enumera el resultado; piensa en ejecución diferida y materialización.",
  },
};
