// engine
import type { QuestionTranslation } from '../../engine/question';

export const translations: Record<string, QuestionTranslation> = {
  'java-primitives-vs-wrapper-null': {
    prompt:
      "```java\npublic class Box {\n    private Integer count;\n\n    public int getCount() {\n        return count;\n    }\n}\n\nBox box = new Box();\nSystem.out.println(box.getCount());\n```\n¿Qué pasa cuando esto se ejecuta?",
    options: {
      a: 'Lanza `NullPointerException`: `count` es un campo `Integer` no inicializado, así que su valor por defecto es `null`, y devolverlo desde un método declarado `int` fuerza el auto-unboxing (`count.intValue()`), que no se puede hacer sobre `null`',
      b: 'Imprime `0`, porque los campos `Integer` tienen por defecto `0`, igual que los campos `int`',
      c: 'No compila, porque un método declarado para devolver `int` no puede hacer `return` de un campo `Integer`',
      d: 'Imprime `null`',
    },
    explanation:
      "`int` e `Integer` son cosas distintas: `int` es un primitivo que siempre tiene un valor y no tiene concepto de `null`, mientras que `Integer` es una referencia a un objeto cuyo valor por defecto (campo de instancia no inicializado) es `null`, no `0` — la opción `b` es incorrecta. `getCount()` compila sin problema (`c` es incorrecta): el compilador hace auto-unboxing de un `Integer` a `int` como valor de retorno insertando una llamada implícita a `count.intValue()`. El problema aparece solo en tiempo de ejecución: `count` es `null`, y llamar a `.intValue()` sobre `null` lanza `NullPointerException` antes de que se imprima nada, así que `d` (que asume que el tipo de retorno primitivo podría de alguna forma contener e imprimir `null`) también es incorrecta. Esta es la trampa clásica del unboxing con NPE: cualquier lugar donde se use un `Integer`, `Long`, `Boolean`, etc. donde se espera un primitivo —una expresión aritmética, un parámetro de método primitivo, un valor de retorno primitivo— hace unboxing implícito, y un wrapper `null` convierte esa llamada implícita en una excepción en tiempo de ejecución.",
  },
  'java-synchronized-keyword-basics': {
    prompt:
      "```java\npublic class Counter {\n    private int count = 0;\n\n    public synchronized void increment() {\n        count++;\n    }\n\n    public int getCount() {\n        return count;\n    }\n}\n```\nDos hilos llaman repetidamente a `increment()` sobre la misma instancia de `Counter`. ¿Qué garantiza marcar `increment()` como `synchronized`?",
    options: {
      a: 'Que solo un hilo a la vez puede ejecutar `increment()` en esta instancia, porque el método adquiere el lock intrínseco sobre `this` antes de ejecutarse y lo libera al retornar — esto evita la condición de carrera de actualización perdida en `count++`',
      b: 'Que `getCount()` también se vuelve seguro para hilos, porque marcar un método como `synchronized` bloquea todos los métodos de la clase, estén o no marcados como `synchronized`',
      c: 'Que `count++` se convierte en una sola instrucción atómica de CPU, así que `synchronized` en realidad no hace falta aquí — los incrementos de `int` ya son seguros para hilos',
      d: '`synchronized` documenta la intención para otros desarrolladores, pero la JVM en realidad no impide que dos hilos ejecuten `increment()` al mismo tiempo',
    },
    explanation:
      "Un método de instancia `synchronized` adquiere el lock intrínseco (el monitor) sobre `this` antes de que se ejecute su cuerpo y lo libera al retornar (de forma normal o por excepción), así que solo un hilo puede estar dentro de `increment()` para una instancia de `Counter` dada en cualquier momento — esa exclusión mutua es exactamente lo que evita la clásica condición de carrera de lectura-modificación-escritura en `count++` (`a` es correcta). `synchronized` no es algo a nivel de clase: solo excluye a otro código que se sincronice sobre el **mismo objeto de lock**; `getCount()` aquí no es `synchronized` en absoluto, así que puede ejecutarse en paralelo con `increment()` y, sin un borde de happens-before, no está garantizado que vea el valor más reciente (`b` es incorrecta). `count++` en realidad son tres pasos separados —leer, sumar uno, escribir de vuelta—, así que dos hilos pueden intercalarse y perder una actualización; precisamente por eso el método necesita `synchronized` (`c` es incorrecta). Y `synchronized` lo hace cumplir la JVM, no es una convención a nivel de comentario: un segundo hilo que llame a `increment()` mientras el lock está tomado realmente se bloquea hasta que se libera (`d` es incorrecta).",
  },
  'java-integer-cache-equality': {
    prompt:
      "```java\nInteger a = 100;\nInteger b = 100;\nSystem.out.println(a == b);\n\nInteger c = 200;\nInteger d = 200;\nSystem.out.println(c == d);\n```\n¿Qué imprime esto?",
    options: {
      a: '`true` y luego `false` — el autoboxing de un literal en `[-128, 127]` pasa por `Integer.valueOf`, que el JLS exige que devuelva una instancia en caché para ese rango, así que `a` y `b` referencian el mismo objeto. `200` queda fuera del rango de la caché, así que cada autoboxing produce un objeto `Integer` nuevo y `c == d` compara dos referencias distintas',
      b: '`true` y luego `true`, porque `Integer` sobrescribe `==` para comparar por valor, igual que `equals`',
      c: '`false` y luego `false`, porque el autoboxing siempre crea un objeto `Integer` completamente nuevo y `==` sobre tipos wrapper siempre compara referencias',
      d: '`true` y luego `false`, pero solo en un depurador; en un build de producción optimizado el JIT interna cada `Integer` boxeado, así que ambos imprimen `true`',
    },
    explanation:
      "`==` sobre tipos wrapper siempre compara **referencias**, nunca valores — Java no tiene sobrecarga de operadores, así que `b` es incorrecta por principio. Pero `Integer.valueOf` (al que llama el autoboxing de un literal) está obligado por el JLS a cachear y reutilizar instancias para valores entre `-128` y `127`, así que boxear `100` dos veces produce el mismo objeto en caché y `a == b` es `true`; `200` queda fuera de ese rango garantizado, así que `c` y `d` normalmente son dos objetos distintos y `c == d` es `false` — esto hace que `c` sea incorrecta, ya que ignora la caché por completo. Nada relacionado con el JIT o el modo de build cambia esto: el cacheo ocurre dentro de `Integer.valueOf` mismo, en cada ejecución, no como un artefacto exclusivo de depuración (`d` es incorrecta). La lección para código real: nunca comparar tipos wrapper con `==` — usa `.equals()` (o desempaqueta a `int` primero) para que la corrección no dependa de un rango de caché interno que la mayoría ni siquiera sabe que existe.",
  },
  'java-list-of-immutability': {
    prompt: "```java\nList<String> names = List.of(\"Ana\", \"Bo\");\nnames.add(\"Cy\");\n```\n¿Qué pasa cuando esto se ejecuta?",
    options: {
      a: '`names.add("Cy")` lanza `UnsupportedOperationException` — `List.of` devuelve una lista genuinamente inmutable, y todo método de modificación estructural (`add`, `remove`, `set`, `clear`) lanza excepción sobre ella',
      b: 'Agrega `"Cy"` sin problema; `List.of` devuelve un simple `ArrayList` redimensionable, igual que `Arrays.asList`',
      c: 'Compila sin problema pero lanza `ArrayIndexOutOfBoundsException`, porque la lista está respaldada por un array de tamaño fijo',
      d: 'No compila, porque `List.of(...)` devuelve `List<String>` y `add` no es un método declarado en la interfaz `List`',
    },
    explanation:
      "`List.of(...)` (Java 9+) devuelve una de las implementaciones inmutables de `List` del JDK: rechaza elementos `null` de entrada y lanza `UnsupportedOperationException` desde todo método que modificaría su estructura (`add`, `remove`, `addAll`, `clear`) o reemplazaría un elemento (`set`) — ese es justamente el propósito de la fábrica. No es un `ArrayList` redimensionable (`b` es incorrecta), y además es más estricta que `Arrays.asList(...)`, que es de tamaño fijo pero aún permite `set` sobre índices existentes; `List.of` prohíbe también eso. El fallo es una `UnsupportedOperationException` en tiempo de ejecución, no una excepción de indexado (`c` es incorrecta — nada aquí siquiera intenta indexar más allá del final). Y `add` compila sin problema: `List` declara `add` como parte de su interfaz (cualquier implementación mutable la soporta), simplemente no está soportada por esta implementación inmutable en particular, así que el fallo solo aparece en tiempo de ejecución (`d` es incorrecta).",
  },
  'java-collectors-groupingby-downstream': {
    prompt:
      "```java\nrecord Employee(String department, double salary) {}\n\nList<Employee> employees = List.of(\n    new Employee(\"eng\", 90_000),\n    new Employee(\"eng\", 110_000),\n    new Employee(\"sales\", 70_000)\n);\n\nMap<String, List<Employee>> byDept = employees.stream()\n    .collect(Collectors.groupingBy(Employee::department));\n\nMap<String, Double> avgSalaryByDept = employees.stream()\n    .collect(Collectors.groupingBy(Employee::department, Collectors.averagingDouble(Employee::salary)));\n```\n¿Cuáles de las siguientes afirmaciones sobre este código son verdaderas? Selecciona todas las que apliquen.",
    options: {
      a: 'Por defecto, `byDept` está respaldado por un `HashMap` plano con valores `ArrayList` mutables — ni el orden de iteración del mapa ni la implementación concreta de `List` de los valores están garantizados',
      b: '`avgSalaryByDept.get("eng")` es `100000.0` — la sobrecarga de dos argumentos de `groupingBy` aplica el colector descendente (aquí `averagingDouble`) a los elementos de cada grupo en lugar de recolectarlos en una `List`',
      c: '`Collectors.groupingBy` siempre devuelve un `LinkedHashMap`, así que `byDept` conserva el orden en que los departamentos aparecieron primero en el stream',
      d: 'Pasar `Collectors.averagingDouble` como colector descendente muta la lista original `employees` en su lugar, reemplazando cada `Employee` con el salario promedio de su departamento',
      e: 'Para obtener un orden garantizado o una implementación específica de `Map` (por ejemplo un `TreeMap` ordenado por nombre de departamento), se necesita la sobrecarga de tres argumentos `groupingBy(classifier, mapFactory, downstream)`',
    },
    explanation:
      "La sobrecarga de un solo argumento `groupingBy(classifier)` recolecta cada grupo en una `List` y devuelve un `HashMap<K, List<V>>` — ni el tipo de mapa ni su orden de iteración forman parte del contrato, y los valores `List` son simples `ArrayList` mutables (`a` es verdadera). La sobrecarga de dos argumentos, `groupingBy(classifier, downstream)`, aplica el `Collector` descendente dado a cada grupo en lugar de usar `toList()` por defecto; `averagingDouble(Employee::salary)` reduce cada grupo al promedio de sus valores de `salary`, así que `\"eng\"` (90 000 y 110 000) promedia a `100000.0` (`b` es verdadera). `groupingBy` **no** devuelve un `LinkedHashMap` por defecto — es un `HashMap`, así que `c` es falsa y el orden de los departamentos no se conserva. Los streams no mutan por diseño: recolectar nunca escribe de vuelta en la lista fuente ni en sus elementos, solo construye un resultado nuevo, así que `d` es falsa — nada cambia en `employees`. Para controlar la implementación del `Map` resultante (para iteración estable, orden, concurrencia, etc.) se necesita la sobrecarga de tres argumentos `groupingBy(classifier, mapFactory, downstream)`, pasando algo como `TreeMap::new` como `mapFactory` (`e` es verdadera).",
  },
  'java-generics-wildcard-pecs': {
    prompt:
      "```java\npublic static void copy(List<? super Number> dest, List<? extends Number> src) {\n    for (Number n : src) {\n        dest.add(n);\n    }\n}\n```\n¿Por qué `src` está declarado `List<? extends Number>` y `dest` está declarado `List<? super Number>` aquí? Recorre el mnemónico PECS, qué permite y prohíbe realmente cada wildcard en tiempo de compilación, por qué un `List<Number>` plano no funcionaría para ninguno de los dos parámetros, y qué significa la erasure de tipos para ambas listas en tiempo de ejecución.",
    modelAnswer:
      "PECS significa \"Producer Extends, Consumer Super\": usa `? extends T` para un parámetro del que solo lees (te \"produce\" valores `T`), y `? super T` para un parámetro en el que solo escribes (te \"consume\" valores `T`). `src` es un productor aquí — el método solo lee `Number`s de él mediante el bucle for-each — así que `List<? extends Number>` permite que quien llama pase un `List<Integer>`, `List<Double>`, o el propio `List<Number>`, y cada elemento leído se ensancha de forma segura a `Number`. El compilador prohíbe llamar a `src.add(...)` (salvo `add(null)`) sobre esa referencia, porque solo sabe que la lista real contiene *algún* subtipo desconocido de `Number` — podría ser un `List<Integer>`, y agregar un `Double` ahí corrompería esa lista, así que el compilador bloquea toda escritura que no pueda demostrarse segura. `dest` es un consumidor — el método solo escribe `Number`s en él mediante `dest.add(n)` — así que `List<? super Number>` permite que quien llama pase un `List<Number>`, `List<Object>`, o cualquier otra lista de un supertipo, y cada llamada a `add(Number)` es segura porque, sea cual sea el tipo real de elemento, está garantizado que es `Number` o un supertipo suyo. A cambio, el compilador restringe la *lectura*: `dest.get(i)` solo devuelve `Object`, porque no puede saber el tipo real, más específico. Un `List<Number>` plano no funcionaría para `src` porque los genéricos de Java son invariantes, no covariantes: `List<Integer>` no es un `List<Number>` aunque `Integer` sea un `Number`, así que quien tuviera un `List<Integer>` no podría llamar a `copy` en absoluto si `src` estuviera tipado como `List<Number>`. Simétricamente, `List<Number>` no funcionaría para `dest` porque quien tuviera un `List<Object>` —un lugar perfectamente válido para guardar `Number`s— no tendría forma de pasarlo, ya que `List<Object>` tampoco es un `List<Number>`. En tiempo de ejecución, los genéricos se borran (erasure): tanto `List<? super Number>` como `List<? extends Number>` se compilan a un simple `List` (tipo raw) en el bytecode — no queda información de wildcard ni de límite para que la JVM la verifique. Toda la seguridad descrita arriba la impone por completo el compilador en el punto de llamada (y mediante casts insertados en las lecturas); es una garantía exclusivamente de tiempo de compilación, que es también la razón por la que no se puede hacer algo como `new List<? extends Number>[10]` ni comprobar `instanceof List<? extends Number>` en tiempo de ejecución — la JVM realmente no lo sabe.",
    rubric: [
      'Enuncia y aplica correctamente PECS: src es un productor (solo se lee de él) así que usa extends, dest es un consumidor (solo se escribe en él) así que usa super',
      'Explica por qué List<? extends Number> prohíbe add(Number) (salvo null) — el compilador solo sabe que hay algún subtipo desconocido de Number detrás, así que un add arbitrario podría corromperla — mientras que las lecturas se ensanchan de forma segura a Number',
      'Explica por qué List<? super Number> permite add(Number) de forma segura pero get(...) solo devuelve Object, ya que el tipo real de elemento podría ser cualquier supertipo de Number',
      'Explica que los genéricos son invariantes (List<Integer> no es un List<Number>), que es por lo que un parámetro List<Number> plano rechazaría a quienes pasan List<Integer> para src o List<Object> para dest',
      'Indica que la erasure de tipos elimina la información de wildcard/límite en tiempo de ejecución — ambos tipos de parámetro son solo List (raw) en el bytecode, y la seguridad es solo de tiempo de compilación',
    ],
    explanation:
      "Esto separa a quienes memorizaron \"PECS\" como un eslogan de quienes entienden *por qué* el compilador permite o prohíbe llamadas específicas sobre cada wildcard, y si saben que esto es enteramente una ficción de tiempo de compilación borrada en runtime — ambas cosas aparecen constantemente en el diseño de APIs de métodos utilitarios genéricos (`Collections.copy`, `Comparator.comparing`, interfaces de repositorio/mapper, etc.).\n\n**Dilo en voz alta:** \"`src` solo produce valores que leo, así que es `? extends Number`; `dest` solo consume valores que escribo, así que es `? super Number` — eso es PECS. Un `List<Number>` plano no aceptaría el `List<Integer>` o `List<Object>` de quien llama porque los genéricos son invariantes, y todo esto se borra a `List` raw en tiempo de ejecución de todas formas.\"",
  },
  'java-hashmap-equals-hashcode-contract': {
    prompt:
      "```java\npublic class Point {\n    private final int x;\n    private final int y;\n\n    public Point(int x, int y) {\n        this.x = x;\n        this.y = y;\n    }\n\n    @Override\n    public boolean equals(Object o) {\n        if (!(o instanceof Point other)) return false;\n        return this.x == other.x && this.y == other.y;\n    }\n}\n\nMap<Point, String> labels = new HashMap<>();\nlabels.put(new Point(1, 2), \"origin-ish\");\n\nSystem.out.println(labels.get(new Point(1, 2)));\n```\n¿Por qué esto imprime `null` en lugar de `\"origin-ish\"`? ¿Cuál es el contrato de `equals`/`hashCode`, y qué más se rompe si lo violas —por ejemplo con una clave mutable cuyos campos relevantes para el hash cambian después de insertarla?",
    modelAnswer:
      "`Point` sobrescribe `equals` pero nunca sobrescribe `hashCode`, así que sigue heredando el `hashCode` por defecto de `Object`, que es esencialmente basado en identidad (derivado de la identidad del objeto, no de sus campos). Las dos instancias `Point(1, 2)` son iguales según `equals()` pero tienen hash codes distintos, esencialmente aleatorios. `HashMap.get` no recorre cada entrada llamando a `equals` en cada una — primero llama a `hashCode()` sobre la clave para calcular un índice de bucket, y solo compara con `equals()` contra lo que ya hay en *ese* bucket. Como las dos instancias probablemente caen en buckets distintos, `get` busca en el bucket equivocado por completo, nunca llega a llamar a `equals` contra la entrada guardada, y devuelve `null`. El contrato formal (del Javadoc de `Object`) es: si `a.equals(b)` es `true`, entonces `a.hashCode() == b.hashCode()` también debe serlo; lo contrario no es obligatorio — dos objetos distintos pueden compartir un hash code, eso es solo una colisión, y `HashMap` resuelve las colisiones recurriendo a `equals()` para cada entrada dentro del mismo bucket. Sobrescribir un método sin el otro rompe ese contrato y rompe silenciosamente toda colección basada en hash construida sobre ese tipo (`HashMap`, `HashSet`, `Hashtable`, `ConcurrentHashMap`) — las búsquedas, `containsKey` y `remove` fallan al encontrar entradas que lógicamente deberían coincidir. Una segunda violación, más insidiosa, es una clave genuinamente mutable: incluso con un par `equals`/`hashCode` *correcto* y consistente, si insertas una clave y luego mutas un campo que ambos métodos leen, el hash code del objeto cambia pero su posición en la tabla no — la entrada queda archivada bajo el bucket de su hash code antiguo mientras que una búsqueda nueva calcula el nuevo, así que la entrada se vuelve inencontrable (`get`, `containsKey` y `remove` para esa clave fallan todos), filtrándola efectivamente dentro del mapa para siempre. La corrección para el bug mostrado es implementar `hashCode` de forma consistente con `equals` (por ejemplo `Objects.hash(x, y)`, o convertir `Point` en un `record`, para el cual el compilador genera ambos automáticamente y de forma consistente). La corrección para el riesgo de clave mutable es más amplia: tratar cualquier objeto usado como clave de `HashMap`/`HashSet` como efectivamente inmutable en todos los campos involucrados en `equals`/`hashCode` — hacer esos campos `final` y no exponer setters para ellos, o directamente no usar un objeto mutable como clave.",
    rubric: [
      'Explica el mecanismo real de búsqueda de HashMap.get: hashCode() elige primero un bucket, y equals() se usa solo para comparar dentro de ese bucket',
      'Indica que el hashCode por defecto de Object está basado en identidad, así que sobrescribir equals sin hashCode da hash codes distintos a objetos iguales, causando que get/put no encuentren entradas que deberían coincidir',
      'Enuncia el contrato formal: los objetos iguales (según equals) deben producir hash codes iguales, mientras que objetos distintos pueden compartir un hash code (una colisión, resuelta con equals dentro del bucket)',
      'Describe el riesgo de clave mutable: mutar un campo relevante para el hash después de insertar cambia el hash code de la clave sin moverla en la tabla, dejando la entrada efectivamente inencontrable/filtrada',
      'Propone una corrección concreta: implementar equals/hashCode de forma consistente (por ejemplo Objects.hash o un record) y tratar los campos relevantes para el hash de las claves de mapas/sets como efectivamente inmutables',
    ],
    explanation:
      "Esta pregunta verifica si \"siempre sobrescribe `hashCode` cuando sobrescribes `equals`\" se entiende mecánicamente —como consecuencia de cómo realmente buscan las tablas hash— en lugar de como una regla memorizada de una advertencia del linter. También saca a la luz si el candidato conoce el modo de fallo más agudo y difícil de depurar: una clave mutable que era correcta al insertarse y luego se vuelve inencontrable para siempre.\n\n**Dilo en voz alta:** \"`HashMap` encuentra un bucket con `hashCode()` y solo entonces compara con `equals()`, así que sobrescribir uno sin el otro hace que objetos iguales caigan en buckets distintos y las búsquedas fallen en silencio — e incluso con ambos sobrescritos correctamente, mutar los campos relevantes para el hash de una clave después de insertarla la deja varada para siempre en el bucket equivocado.\"",
  },
  'java-completablefuture-composition': {
    prompt:
      "Estás llamando a dos servicios remotos independientes y quieres combinar sus resultados con el manejo de errores adecuado, sin bloquear el hilo que llama:\n```java\nCompletableFuture<User> userFuture = CompletableFuture.supplyAsync(() -> fetchUser(userId));\nCompletableFuture<List<Order>> ordersFuture = CompletableFuture.supplyAsync(() -> fetchOrders(userId));\n\nCompletableFuture<UserSummary> summary = userFuture\n    .thenCombine(ordersFuture, (user, orders) -> new UserSummary(user, orders))\n    .exceptionally(ex -> UserSummary.empty());\n```\nRecorre qué hacen `thenCombine` y `exceptionally` aquí, y cuándo usarías `thenCompose` en lugar de `thenApply`. ¿Qué tiene de malo llamar a `supplyAsync` sin un `Executor` explícito en una aplicación de servidor, y cómo lo corregirías? ¿En qué se diferencia `exceptionally` de `handle`?",
    modelAnswer:
      "`thenCombine` registra un callback que se dispara una vez que **ambos** `userFuture` y `ordersFuture` han completado con éxito, aplicando la `BiFunction` dada a sus dos resultados y produciendo un nuevo `CompletableFuture<UserSummary>` — nunca bloquea el hilo que llama; solo conecta una continuación que algún hilo (uno del pool común o de un executor) ejecutará después. `thenApply` y `thenCompose` se diferencian en lo que devuelve la función de mapeo: `thenApply(Function<T,R>)` es para una transformación síncrona sencilla que devuelve un valor `R` directamente; `thenCompose(Function<T, CompletableFuture<R>>)` es para encadenar otro paso *asíncrono* cuya función devuelve a su vez un `CompletableFuture<R>` — lo aplana, igual que hacen `Optional.flatMap`/`Stream.flatMap`. Usar `thenApply` con una función que devuelve un `CompletableFuture<X>` produciría un `CompletableFuture<CompletableFuture<X>>` anidado, lo cual casi siempre es un bug (habría que desenvolverlo de nuevo); `thenCompose` evita ese anidamiento. `exceptionally(Function<Throwable,T>)` solo se ejecuta en la ruta de **fallo** — si `userFuture` u `ordersFuture` (o la función de `thenCombine` misma) lanza, esto produce un `UserSummary.empty()` de respaldo; si nada falló, `exceptionally` se omite por completo y el `UserSummary` exitoso pasa sin cambios. `handle(BiFunction<T,Throwable,R>)` se diferencia en que se ejecuta en **ambas** rutas —éxito y fallo—, recibiendo siempre uno de los dos como `null`, y siempre produce un resultado nuevo; es la herramienta correcta cuando necesitas observar o reaccionar al resultado sin importar si tuvo éxito (registrar en ambos casos, o transformar también un valor exitoso), mientras que `exceptionally` (y su hermano `whenComplete`, que observa pero no transforma) es más limitado. El bug del fragmento tal como está: `supplyAsync` sin segundo argumento ejecuta su supplier en `ForkJoinPool.commonPool()`, un pool compartido, a nivel de toda la JVM, dimensionado aproximadamente según el número de núcleos de CPU. Si `fetchUser`/`fetchOrders` hacen I/O bloqueante (una llamada JDBC bloqueante, un cliente HTTP bloqueante), esos hilos quedan bloqueados en ese pool compartido, dejando sin recursos a cualquier otro componente de la JVM que también dependa del pool común por defecto —incluidos los streams paralelos. La corrección es pasar un `Executor` explícito y dedicado: `CompletableFuture.supplyAsync(() -> fetchUser(userId), executor)`, donde `executor` es un pool acotado dimensionado para I/O bloqueante y aislado del pool común; desde Java 21, si el trabajo es genuinamente de I/O bloqueante, `Executors.newVirtualThreadPerTaskExecutor()` también es una opción razonable, ya que los hilos virtuales son suficientemente baratos como para que bloquear uno no deje sin recursos a un pool limitado de hilos de plataforma, como sí pasa al bloquear un hilo del pool común.",
    rubric: [
      'Explica que thenCombine registra un callback que se ejecuta una vez que ambos futures completan con éxito, combinando sus resultados sin bloquear el hilo que llama',
      'Explica la distinción entre thenApply y thenCompose: thenApply para una transformación síncrona sencilla, thenCompose cuando la función de mapeo devuelve a su vez un CompletableFuture, para evitar un CompletableFuture<CompletableFuture<T>> anidado',
      'Explica que exceptionally solo se ejecuta en la ruta de fallo y aporta un valor de respaldo, mientras que handle se ejecuta en éxito y fallo y puede transformar cualquiera de los dos resultados',
      'Indica que supplyAsync sin argumento Executor se ejecuta en el ForkJoinPool.commonPool() compartido, y que el I/O bloqueante ahí deja sin recursos a otros consumidores de ese pool',
      'Propone una corrección: pasar un Executor dedicado/acotado, mencionando opcionalmente los hilos virtuales de Java 21 (Executors.newVirtualThreadPerTaskExecutor()) como alternativa para trabajo de I/O bloqueante',
    ],
    explanation:
      "Esto evalúa si la composición de `CompletableFuture` se entiende como la construcción de un pipeline de callbacks sin bloqueo —no solo como una envoltura ligeramente más agradable sobre `Future.get()`— y si el candidato conoce el error de producción muy común de dejar que trabajo bloqueante corra por omisión en el pool común compartido.\n\n**Dilo en voz alta:** \"`thenCombine` espera a ambos futures sin bloquear a quien llama, `thenCompose` evita el anidamiento cuando el siguiente paso es en sí asíncrono, y `exceptionally` solo cubre la ruta de fallo mientras que `handle` ve ambos resultados; y nunca dejo que I/O bloqueante corra en el `ForkJoinPool.commonPool()` por defecto — paso un executor explícito, o uso hilos virtuales para eso en Java 21.\"",
  },
};
