// engine
import type { QuestionTranslation } from '../../engine/question';

export const translations: Record<string, QuestionTranslation> = {
  'aspnet-middleware-basics': {
    prompt:
      '```csharp\nvar app = builder.Build();\n\napp.Use(async (context, next) =>\n{\n    Console.WriteLine("Before");\n    await next(context);\n    Console.WriteLine("After");\n});\n\napp.MapGet("/", () => "Hello");\n\napp.Run();\n```\n¿Qué describe mejor el middleware de ASP.NET Core, a partir de este ejemplo?',
    options: {
      a: 'El middleware es una cadena de componentes que reciben cada uno el `HttpContext` y un delegado hacia el siguiente componente; cada uno puede ejecutar código antes y después de llamar a ese delegado, así que las peticiones "entran" a través de la cadena en el orden de registro y las respuestas "salen" en orden inverso',
      b: 'El middleware se ejecuta una sola vez, al arrancar la aplicación; el código dentro de `app.Use` se ejecuta cuando se llama a `app.Run()` (el que arranca el host, al final de `Program.cs`), no en cada petición HTTP entrante',
      c: 'Todo componente de middleware debe llamar a `next` exactamente una vez y nunca puede ejecutar código después de hacerlo; cualquier cosa escrita después de `await next(context)` es ignorada por el runtime',
      d: '`app.Use` solo puede registrar middleware que se ejecute antes de que ocurra el enrutamiento; no es posible escribir middleware que se ejecute después de que un endpoint ya produjo una respuesta',
    },
    explanation:
      'Los componentes de middleware están encadenados: cada uno recibe el `HttpContext` actual y un delegado `next` que representa el resto del pipeline, decide si (y cuándo) llamar a `next`, y puede ejecutar lógica tanto antes como después de esa llamada — por eso se imprime "Before", luego `next` ejecuta el resto del pipeline (el enrutamiento, el endpoint `/`), y luego se imprime "After" una vez que el control regresa. La opción b es incorrecta: el `app.Run()` que arranca el host, al final de `Program.cs`, no tiene relación con la sobrecarga de middleware terminal que también se llama `Run`, y el delegado de `app.Use` se ejecuta en cada petición que coincide, no una sola vez al arrancar. La opción c está al revés — ejecutar código después de `await next(context)` es la forma normal y soportada de observar la respuesta en su camino de vuelta, y es exactamente lo que hace posible el middleware de logging/medición de tiempos. La opción d también es incorrecta: el middleware registrado en cualquier parte del pipeline, incluso después del enrutamiento, puede seguir ejecutando lógica después de que `next` retorna, es decir, después de que el endpoint ya escribió su respuesta — así funciona el middleware que inspecciona la respuesta (compresión, registro de códigos de estado, etcétera).',
  },
  'aspnet-controller-di-and-routing': {
    prompt:
      '```csharp\n[ApiController]\n[Route("api/[controller]")]\npublic class OrdersController : ControllerBase\n{\n    private readonly IOrderService _orders;\n\n    public OrdersController(IOrderService orders)\n    {\n        _orders = orders;\n    }\n\n    [HttpGet("{id}")]\n    public IActionResult GetById(int id)\n    {\n        var order = _orders.Find(id);\n        if (order is null)\n        {\n            return NotFound();\n        }\n        return Ok(order);\n    }\n}\n```\n¿Cuál afirmación describe correctamente este controlador?',
    options: {
      a: '`IOrderService orders` es entregado por inyección de dependencias cuando el controlador se activa para una petición, siempre que `IOrderService` esté registrado en `builder.Services`; `[Route("api/[controller]")]` mapea las peticiones a `/api/Orders` (el token `[controller]` se reemplaza por el nombre de la clase sin el sufijo `Controller`), y `[HttpGet("{id}")]` se combina con eso para coincidir con `GET /api/Orders/{id}`',
      b: '`IOrderService orders` debe resolverse manualmente dentro del constructor con `HttpContext.RequestServices.GetService<IOrderService>()`; la inyección por constructor no está soportada en los controladores de ASP.NET Core',
      c: '`[ApiController]` es lo que hace que la ruta sea alcanzable; sin él, los atributos `[HttpGet]` y `[Route]` se ignoran y `GetById` nunca puede invocarse',
      d: 'Como `GetById` devuelve `IActionResult`, la respuesta siempre se serializa como XML a menos que el cliente envíe explícitamente el encabezado `Accept: application/json` — JSON solo es un formato de reserva negociado',
    },
    explanation:
      'La factoría de controladores de ASP.NET Core resuelve los parámetros del constructor desde el contenedor de DI cuando activa un controlador para una petición, exactamente igual que con cualquier otra clase gestionada por DI — no hace falta ninguna búsqueda manual con `HttpContext.RequestServices`, lo cual hace incorrecta la opción b. `[Route("api/[controller]")]` combinado con el enrutamiento por atributos en la acción produce `api/Orders/{id}`, que coincide con `[HttpGet("{id}")]` de `GetById`. La opción c exagera lo que hace `[ApiController]`: el enrutamiento por atributos y `[HttpGet]`/`[Route]` también funcionan en una clase `ControllerBase` normal; `[ApiController]` agrega comodidades encima (respuestas 400 automáticas para un model state inválido, inferencia de fuentes de binding y exigir enrutamiento por atributos), pero no determina si la ruta es alcanzable. La opción d es incorrecta porque JSON, no XML, es el formateador de salida por defecto (y normalmente el único) registrado en ASP.NET Core; un formateador XML solo participa en la negociación de contenido si se agrega explícitamente con `AddXmlSerializerFormatters()`.',
  },
  'aspnet-use-vs-run-mismatch': {
    prompt:
      '```csharp\napp.Use(async (context, next) =>\n{\n    if (context.Request.Path == "/health")\n    {\n        await context.Response.WriteAsync("OK");\n        return;\n    }\n    await next(context);\n});\n\napp.Run(async context =>\n{\n    await context.Response.WriteAsync("fallback");\n});\n\napp.MapGet("/hello", () => "hi");\n```\nUna petición a `GET /hello` devuelve `fallback` en lugar de `hi`. ¿Por qué, y cuál es la solución?',
    options: {
      a: '`app.Run` registra middleware **terminal**: su delegado no recibe parámetro `next` y siempre escribe una respuesta, terminando ahí mismo el pipeline. Se registró antes de `app.MapGet("/hello", ...)`, así que cualquier petición que no sea `/health` llega a `app.Run` y es atendida por él antes de que la lógica de enrutamiento/ejecución de endpoint que agrega `MapGet` (en el punto de `Program.cs` donde se llama) tenga siquiera oportunidad de actuar. Solución: mover `app.MapGet` antes del `app.Run` incondicional, o eliminar el bloque `app.Run` que actúa como catch-all',
      b: '`app.Run` y `app.MapGet` no se pueden combinar en el mismo pipeline; cualquier llamada a `Map*` debe ser el primer statement después de `app.Build()`',
      c: 'El bloque `app.Use` para `/health` es el error: su comparación de path se aplica en silencio a cualquier petición, incluida `/hello`, sin importar el `if` que se muestra',
      d: '`app.Run` solo se ejecuta si ningún otro middleware llamó a `next`, así que `app.MapGet("/hello", ...)` debería seguir ejecutándose primero de forma automática, porque el emparejamiento de rutas siempre se inserta al principio del pipeline sin importar dónde aparezca `app.Run` en `Program.cs`',
    },
    explanation:
      'El middleware de `app.Use` recibe un delegado `next` y decide si lo llama; el middleware de `app.Run` no recibe ninguno — su firma es simplemente `(HttpContext) => Task`, así que por definición nunca puede reenviar la petición y siempre produce una respuesta por sí mismo. Eso hace que el orden de registro sea decisivo aquí: para cualquier ruta distinta de `/health`, el bloque `app.Use` condicional llama a `next`, que entrega el control a lo que se haya registrado después de él — y eso es el `app.Run` incondicional, registrado antes que `MapGet("/hello", ...)`. La lógica de enrutamiento/ejecución del endpoint `hello` se inserta efectivamente en el pipeline en el punto donde se llama a `MapGet` en `Program.cs`, que aquí es *después* de que `app.Run` ya absorbió la petición. La opción b es falsa — las llamadas a `Run` y a `Map*` se pueden intercalar libremente; solo importa su orden relativo. La opción c es falsa — el `if` sí limita correctamente la respuesta anticipada solo a `/health`. La opción d es falsa y es exactamente el error de concepto que esta trampa busca detectar: nada en el modelo de hosting minimalista hace que el enrutamiento salte al frente del pipeline sin importar dónde se llame a `Map*` — el orden del código en `Program.cs` sigue determinando dónde se ubica cada pieza de middleware en la cadena, incluido el comportamiento implícito de enrutamiento/ejecución de endpoint que agrega `Map*`.',
  },
  'aspnet-minimal-api-frombody-inference': {
    prompt:
      '```csharp\npublic record CreateOrderRequest(string CustomerId, List<string> ItemIds);\n\napp.MapPost("/orders", (CreateOrderRequest request, IOrderService orders) =>\n{\n    var id = orders.Create(request.CustomerId, request.ItemIds);\n    return Results.Created($"/orders/{id}", new { id });\n});\n```\n`IOrderService` está registrado en `builder.Services`. Un cliente hace un `POST` con `{"customerId": "c1", "itemIds": ["i1"]}` como cuerpo de la petición. ¿Cómo se vinculan `request` y `orders`, y por qué solo uno de ellos viene del cuerpo?',
    options: {
      a: '`orders` se infiere como un servicio provisto por DI porque `IOrderService` es un tipo de servicio registrado, así que se resuelve desde el `IServiceProvider` de la petición; `request` no tiene ninguna otra fuente de binding (no hay un valor de ruta o de query llamado `request`, no es un servicio registrado, no tiene `TryParse`/`BindAsync`), así que un endpoint minimal API recurre a vincular un parámetro como ese desde el cuerpo JSON de la petición. Solo un parámetro puede vincularse implícitamente desde el cuerpo de esta forma',
      b: 'Ambos parámetros se vinculan desde el cuerpo: las minimal APIs deserializan el payload JSON de forma independiente en cada parámetro de tipo complejo, repartiendo las propiedades por nombre entre ellos',
      c: '`orders` se vincula desde el cuerpo porque se declara en segundo lugar en la lista de parámetros, y `request` se resuelve desde DI porque los tipos `record` siempre se tratan como servicios en el model binding de minimal APIs',
      d: 'Las minimal APIs requieren un atributo `[FromBody]` explícito en `request`; sin él, el endpoint lanza `InvalidOperationException` al arrancar porque la fuente de binding para un parámetro `record` nunca puede inferirse',
    },
    explanation:
      'El binding de parámetros de minimal APIs revisa, por cada parámetro, si coincide con una fuente conocida antes de recurrir al cuerpo: valores de ruta, cadena de consulta, encabezados, atributos explícitos, tipos especiales del framework y — algo importante — si el tipo del parámetro está registrado como servicio en el contenedor de DI. `IOrderService` coincide con ese último caso, así que `orders` se resuelve desde el proveedor de servicios de la petición en lugar de parsearse desde el JSON. `request` no coincide con ninguna de esas fuentes (no hay un valor de ruta o de query llamado `request`, y `CreateOrderRequest` no es un servicio registrado), así que el framework lo trata como el parámetro implícito del cuerpo y deserializa el payload JSON en él. Solo un parámetro puede provenir del cuerpo de esta forma — un segundo tipo complejo sin atributo y sin otra fuente de binding produce un error de binding en tiempo de ejecución en lugar de repartirse entre ambos. Las opciones b y c inventan reglas de binding que ASP.NET Core no tiene (división de JSON por parámetro, e inferencia por posición o por ser un `record`); la opción d es incorrecta porque `[FromBody]` es opcional aquí precisamente porque la inferencia de fuente de binding ya lo resuelve correctamente, y no hay ninguna excepción en tiempo de arranque para este caso.',
  },
  'aspnet-401-vs-403-policy': {
    prompt:
      '```csharp\n[Authorize(Policy = "CanEditOrders")]\n[HttpPut("{id}")]\npublic IActionResult Update(int id, OrderDto dto) { /* ... */ }\n```\nEl cliente A llama a este endpoint sin ningún encabezado `Authorization`. El cliente B lo llama con un token JWT bearer válido y correctamente firmado, de un usuario real que simplemente no cumple la política `CanEditOrders`. ¿Qué código de estado recibe cada uno, y por qué?',
    options: {
      a: 'El cliente A recibe `401 Unauthorized`, porque el handler de autenticación no puede establecer ninguna identidad para la petición, lo cual dispara un "challenge". El cliente B recibe `403 Forbidden`, porque la autenticación tiene éxito (existe un `ClaimsPrincipal` válido), pero la autorización evalúa la política `CanEditOrders` contra ese principal y falla, lo cual dispara un "forbid" en lugar de un challenge',
      b: 'Ambos clientes reciben `401 Unauthorized`; `[Authorize(Policy = ...)]` no puede distinguir "sin ninguna identidad" de "identidad presente pero política fallida" — por diseño, ambos fallos producen el mismo código de estado',
      c: 'El cliente A recibe `403 Forbidden` (la falta de credenciales se trata como una denegación de acceso) y el cliente B recibe `401 Unauthorized` (un usuario autenticado que falla una política se trata como si nunca se hubiera autenticado)',
      d: 'Ambos clientes reciben `500 Internal Server Error`, porque la evaluación de la política se ejecuta antes que la autenticación en el pipeline, así que `HttpContext.User` todavía no existe cuando se comprueba `CanEditOrders` y la petición lanza una excepción no controlada',
    },
    explanation:
      'La autenticación y la autorización son dos modos de fallo distintos con dos respuestas distintas. Cuando no se presentan credenciales (o son inválidas), el middleware de autorización le pide al handler de autenticación que "desafíe" la petición, lo cual para autenticación JWT bearer sin alternativa interactiva significa un `401`. Cuando las credenciales son válidas y existe un `ClaimsPrincipal`, pero ese principal no cumple la política requerida, la respuesta es en cambio un "forbid" — `403` — porque el servidor sabe exactamente quién está preguntando y se niega a propósito, lo cual es una situación materialmente distinta de "no sé quién es esto". Las opciones b y c colapsan o invierten esa distinción; la opción d es incorrecta porque `UseAuthentication` se ejecuta, y llena `HttpContext.User`, antes de que `UseAuthorization` evalúe cualquier atributo `[Authorize]` — aquí no hay excepción alguna, solo dos resultados distintos y bien definidos.',
  },
  'aspnet-middleware-pipeline-tradeoffs': {
    prompt: '¿Qué afirmaciones sobre el pipeline de middleware de ASP.NET Core, el enrutamiento por endpoints y el manejo de excepciones son correctas? Selecciona todas las que apliquen.',
    options: {
      a: '`UseAuthentication` debe registrarse antes que `UseAuthorization`, porque el middleware de autorización lee `HttpContext.User`, que es responsabilidad del middleware de autenticación llenar; registrarlos en el orden inverso hace que la autorización siempre evalúe contra un principal no autenticado',
      b: 'En el modelo de hosting minimalista, incluso si `Program.cs` nunca llama explícitamente a `UseRouting`/`UseEndpoints`, `WebApplication` igual conecta automáticamente un comportamiento equivalente de enrutamiento y ejecución de endpoint — el emparejamiento de rutas ocurre cerca de donde se configuran los endpoints, y el endpoint que coincide en realidad se ejecuta en el punto de `Program.cs` donde aparece la llamada correspondiente a `Map*`/`MapControllers` — así que la posición de otro middleware respecto a esas llamadas `Map*` sigue determinando si se ejecuta antes del emparejamiento, entre el emparejamiento y la ejecución, o después de que ya se produjo una respuesta',
      c: '`UseExceptionHandler`, registrado cerca del inicio del pipeline, puede capturar excepciones no controladas lanzadas por cualquier componente posterior — enrutamiento, autenticación, autorización, middleware personalizado y ejecución de acciones de MVC por igual — mientras que un *filter* de excepciones de MVC solo observa excepciones lanzadas dentro del pipeline de invocación de la acción (model binding, ejecución de la acción, filters de acción/resultado) y nunca ve una excepción lanzada por middleware que se ejecuta antes o después de esa maquinaria',
      d: 'Los filters de excepciones ven las excepciones lanzadas por cualquier middleware anterior en el pipeline, no solo las que se generan durante la ejecución de la acción, porque los filters de MVC envuelven todo el pipeline de la petición y no solo la acción del controlador',
      e: 'Registrar `UseAuthorization` antes que `UseAuthentication` es inofensivo siempre que `[Authorize]` esté presente en la acción, porque `UseAuthorization` dispara el proceso de autenticación por sí mismo cada vez que `HttpContext.User` todavía no se ha establecido',
      f: 'Un middleware que nunca llama a `next()` (o `next.Invoke()`) corta el pipeline en seco: nada de lo registrado después de él — ni siquiera la ejecución de un endpoint que coincida — se ejecuta para esa petición, a menos que ese mismo middleware ya haya producido la respuesta',
    },
    explanation:
      'El orden del pipeline no es una preferencia de estilo en ASP.NET Core; varios componentes dependen estrictamente de lo que se ejecutó antes que ellos. `UseAuthorization` inspecciona `HttpContext.User`, que solo existe porque `UseAuthentication` se ejecutó primero y lo llenó a partir de las credenciales de la petición — invertir el orden hace que cada verificación `[Authorize]` evalúe contra un principal anónimo, sin importar cuán válido sea en realidad el token del llamador. El enrutamiento por endpoints se comporta igual incluso cuando es implícito: el modelo de hosting minimalista inserta automáticamente el comportamiento de enrutamiento y ejecución de endpoint cuando se omiten `UseRouting`/`UseEndpoints`, pero lo hace en la posición que implica `Program.cs` (cerca de las llamadas `Map*`), no moviéndose mágicamente al frente — un middleware terminal o que corta el pipeline, registrado antes de esas llamadas, sigue ejecutándose primero, que es exactamente el mismo mecanismo detrás de la trampa de `app.Run` y detrás de la opción f. El middleware `UseExceptionHandler` se ubica en el pipeline como cualquier otro middleware, así que si está lo bastante temprano, envuelve y puede capturar excepciones de todo lo que está después de él, incluido MVC; un filter de excepciones de MVC, en cambio, es parte de la maquinaria misma de invocación de la acción, así que su alcance se limita a esa maquinaria — no puede ver una excepción lanzada por el enrutamiento, la autenticación o un middleware personalizado, que es exactamente lo que hace falsa a la opción d y verdadera a la opción c. La opción e invierte una dependencia real: la autorización no realiza la autenticación como efecto secundario; solo lee la identidad que la autenticación ya estableció, así que ejecutarla primero significa que nunca ve ninguna identidad válida.\n\n**Dilo en voz alta:** "Mantengo `UseAuthentication` antes que `UseAuthorization` porque la autorización solo lee el principal que construye la autenticación, tengo presente que la ejecución del endpoint ocurre donde se llama a `Map*` aunque el enrutamiento sea implícito, y pongo el middleware de manejo de excepciones amplio temprano en el pipeline porque los filters solo pueden capturar lo que ocurre dentro del propio pipeline de invocación de acciones de MVC, no nada anterior."',
  },
  'aspnet-minimal-api-vs-controllers-tradeoffs': {
    prompt:
      'Tu equipo va a agregar una nueva superficie HTTP de lectura/escritura para recursos `Order` en una app de .NET 8/9 que ya aloja varios controladores MVC bien establecidos. Discute los trade-offs entre construir los nuevos endpoints como minimal APIs (`MapGet`/`MapPost` sobre `WebApplication`) o como un controlador MVC, cómo moldearías las respuestas de la minimal API usando `IResult`/`TypedResults` si eligieras ese camino, y por qué agregarías un parámetro `CancellationToken` a los handlers en cualquiera de los dos casos.',
    modelAnswer:
      'Las minimal APIs y los controladores terminan ambos despachando a un método de C# a través del enrutamiento, pero difieren en la sobrecarga y en cuánta estructura obtienes gratis. Las minimal APIs se saltan el pipeline de filters de MVC y la maquinaria de activación de controladores, así que hay menos indirección por petición y menos boilerplate para un conjunto de endpoints pequeño y enfocado — pero eso también significa que se pierden cosas que `[ApiController]` da gratis a los controladores, sobre todo: sin trabajo extra, los handlers de minimal API no ejecutan automáticamente la validación de DataAnnotations sobre un modelo vinculado ni cortan con un `400 ValidationProblemDetails` como sí hace un controlador decorado con `[ApiController]`, así que la validación hay que hacerla explícitamente (dentro del handler o mediante un filter agregado). Los controladores también traen el pipeline completo de filters de acción/excepción/resultado, que es valioso cuando el comportamiento transversal (logging, caché, validación, verificaciones de autorización que necesitan correr en una etapa específica) ya está expresado como filters en el resto de la app — reutilizar eso de forma consistente es un argumento real para quedarse con controladores en un código base que ya tiene varios, solo por consistencia e infraestructura compartida, aunque una superficie nueva y aislada funcionaría igual de bien como minimal APIs. Si optara por minimal APIs, devolvería `IResult` desde `TypedResults` (por ejemplo, `TypedResults.Ok(order)`, `TypedResults.NotFound()`, `TypedResults.Created($"/orders/{id}", order)`) en lugar de los equivalentes sin tipar de `Results.*`, por dos razones concretas: los tipos de retorno concretos `Ok<Order>`/`NotFound` hacen que el handler sea más fácil de probar unitariamente (se puede aserir sobre el tipo de resultado real y su `Value`, en lugar de solo sobre la respuesta escrita en un `HttpContext` falso), y permiten que el framework infiera metadatos de respuesta OpenAPI precisos directamente de la firma del método, sin necesitar llamadas a `.Produces<Order>()` agregadas después. En cualquiera de los dos casos — minimal API o controlador — agregaría un parámetro `CancellationToken` al handler/acción; ASP.NET Core lo vincula automáticamente a `HttpContext.RequestAborted`, y pasarlo a la consulta de EF Core o a la llamada posterior de `HttpClient` permite que ese trabajo realmente se detenga cuando el llamador se desconecta, en lugar de que el servidor siga reteniendo una conexión a la base de datos y haciendo trabajo para una respuesta que nadie va a recibir jamás.',
    rubric: [
      'Indica al menos un costo concreto de las minimal APIs respecto a los controladores (por ejemplo, no hay validación automática de DataAnnotations ni corte de model-state como el que da [ApiController]) y al menos un beneficio concreto (menos overhead/boilerplate, o ausencia del pipeline de filters de MVC)',
      'Indica al menos una razón concreta para preferir controladores en este caso específico, vinculada a los controladores MVC ya existentes en la app (filters/convenciones/consistencia compartidos), en lugar de declarar un enfoque universalmente mejor',
      'Explica que TypedResults devuelve tipos de resultado concretos (frente a Results.* sin tipar), y conecta eso con mejor capacidad de pruebas unitarias y/o generación precisa de metadatos OpenAPI a partir de la firma del método',
      'Indica que un parámetro CancellationToken en el handler se vincula a HttpContext.RequestAborted y explica por qué importa propagarlo a las llamadas asíncronas posteriores (evitar trabajo/conexiones de base de datos desperdiciados cuando el cliente se desconecta)',
      'Aplica el razonamiento tanto a minimal APIs como a controladores, en lugar de tratar el CancellationToken o la discusión de trade-offs como específicos de uno solo de los dos',
    ],
    explanation:
      'Esta pregunta deliberadamente no busca "las minimal APIs son más rápidas" como toda la respuesta — la parte interesante es reconocer que perder la validación automática de `[ApiController]` es un costo real, que `TypedResults` existe específicamente para recuperar la capacidad de pruebas y la precisión de OpenAPI que perdería un tipo de retorno `IResult` sin tipar, y que el punto del CancellationToken aplica de forma uniforme sin importar qué estilo de hosting gane.\n\n**Dilo en voz alta:** "Las minimal APIs te cuestan la validación automática de model-state y el pipeline de filters que dan los controladores con `[ApiController]`, así que en un código base que ya se apoya en controladores mantendría la consistencia; si usara minimal APIs devolvería `TypedResults` por capacidad de pruebas y metadatos OpenAPI precisos, y en cualquier caso aceptaría un `CancellationToken` para que las peticiones abandonadas dejen de trabajar en lugar de completarse para nadie."',
  },
  'aspnet-jwt-bearer-policy-authorization': {
    prompt:
      'Diseña la autorización para `PUT /orders/{id}` de forma que solo el dueño de la orden, o un usuario con el rol `OrdersManager`, pueda actualizarla. Explica cómo valida ASP.NET Core el token JWT bearer entrante en primer lugar, luego explica por qué un simple `[Authorize(Roles = "OrdersManager")]` no basta por sí solo para esta regla, y qué agrega un requirement/handler personalizado que una verificación de rol por sí sola no puede.',
    modelAnswer:
      'La validación del JWT bearer se configura mediante `AddAuthentication(...).AddJwtBearer(options => options.TokenValidationParameters = new TokenValidationParameters { ValidateIssuer = true, ValidIssuer = ..., ValidateAudience = true, ValidAudience = ..., ValidateLifetime = true, ValidateIssuerSigningKey = true, IssuerSigningKey = ... })`. En cada petición, el handler de JWT bearer verifica la firma del token contra la clave de firma configurada, y verifica el emisor, la audiencia y la expiración contra esos `TokenValidationParameters`; si todas las comprobaciones pasan, construye un `ClaimsPrincipal` a partir de los claims del token y lo asigna a `HttpContext.User` (esto solo surte efecto para el middleware posterior porque `UseAuthentication` se ejecuta antes que `UseAuthorization`). `[Authorize(Roles = "OrdersManager")]` por sí solo puede expresar la rama de "manager" de la regla, pero no puede expresar "o es el dueño de esta orden específica", porque una verificación de rol solo mira los claims que ya están presentes en el principal — no tiene forma de comparar esos claims contra la `Order` específica que se está actualizando, ya que el atributo se evalúa antes de que el recurso siquiera se cargue. Para combinar ambas ramas, definiría un `IAuthorizationRequirement` personalizado (por ejemplo, `SameOwnerOrRoleRequirement`) y un `AuthorizationHandler<SameOwnerOrRoleRequirement, Order>` tipado por recurso, cuyo `HandleRequirementAsync` cumple el requirement si `context.User.IsInRole("OrdersManager")` es verdadero, o si el id del dueño de la orden coincide con un claim de id en `context.User`. Lo registraría con `services.AddAuthorization(options => options.AddPolicy("CanEditOrder", policy => policy.Requirements.Add(new SameOwnerOrRoleRequirement())))` y `services.AddSingleton<IAuthorizationHandler, SameOwnerOrRoleHandler>()`. Como esto es autorización basada en recurso — la decisión depende de la `Order` específica, no solo de los claims del llamador — no puede expresarse por completo con un atributo `[Authorize]` declarativo en la acción; en su lugar, la acción carga primero la orden, luego llama a `await _authorizationService.AuthorizeAsync(User, order, "CanEditOrder")` y devuelve `Forbid()` (403) si eso falla.',
    rubric: [
      'Describe la validación de JWT bearer mediante TokenValidationParameters (emisor, audiencia, expiración, clave de firma) e indica que el éxito llena HttpContext.User con claims para el middleware posterior',
      'Indica que una verificación de rol por sí sola no puede expresar la titularidad de un recurso específico porque solo inspecciona claims ya presentes en el principal, no la entidad sobre la que se actúa',
      'Describe definir un IAuthorizationRequirement personalizado más un AuthorizationHandler<TRequirement> (idealmente tipado por recurso) registrado mediante AddPolicy/AddAuthorization',
      'Indica que la autorización basada en recurso requiere una llamada imperativa a IAuthorizationService.AuthorizeAsync(user, resource, policy) después de cargar la entidad, ya que un atributo [Authorize] declarativo se ejecuta antes de que el recurso exista',
      'Produce una regla combinada coherente (rol OrdersManager O coincidencia de titularidad) en lugar de cubrir solo una de las dos ramas',
    ],
    explanation:
      'La trampa de este escenario es detenerse en `[Authorize(Roles = "OrdersManager")]` y no notar que eso descarta por completo, en silencio, la rama de titularidad de la regla, porque una verificación de rol declarativa no tiene forma de ver el recurso que se está modificando — se ejecuta, y termina, antes de que la acción siquiera cargue la `Order`.\n\n**Dilo en voz alta:** "Un atributo de rol puede expresar la rama de manager pero no la titularidad de esta orden específica, porque nunca ve el recurso — así que agregaría un requirement y un handler basados en recurso, lo registraría como política, y llamaría a `AuthorizeAsync` contra la orden ya cargada en lugar de intentar forzar todo en un solo atributo."',
  },
};
