// engine
import type { QuestionTranslation } from '../../engine/question';

export const translations: Record<string, QuestionTranslation> = {
  'aspnet-middleware-basics': {
    prompt:
      '```csharp\nvar app = builder.Build();\n\napp.Use(async (context, next) =>\n{\n    Console.WriteLine("Before");\n    await next(context);\n    Console.WriteLine("After");\n});\n\napp.MapGet("/", () => "Hello");\n\napp.Run();\n```\n¿Qué describe mejor el middleware de ASP.NET Core, a partir de este ejemplo?',
    options: {
      a: 'El middleware se ejecuta una sola vez, al arrancar la aplicación; el código dentro de `app.Use` se ejecuta cuando se llama a `app.Run()`, el que arranca el host al final de `Program.cs`, no en cada petición entrante',
      b: 'El middleware es una cadena de componentes, cada uno recibe `HttpContext` y un delegado `next`; cada uno puede ejecutar código antes y después de llamar a `next`, así que las respuestas regresan por la cadena en orden inverso',
      c: 'Todo componente de middleware debe llamar a `next` exactamente una vez y nunca puede ejecutar código después de hacerlo; una comprobación del runtime lanza una excepción si aparece código después de `await next(context)`',
      d: '`app.Use` solo puede registrar middleware que se ejecute antes de que ocurra el enrutamiento; un paso de registro aparte conecta automáticamente cualquier middleware pensado para ejecutarse después de que un endpoint produjo una respuesta',
    },
    explanation:
      'Los componentes de middleware están encadenados: cada uno recibe el `HttpContext` actual y un delegado `next` que representa el resto del pipeline, decide si (y cuándo) llamar a `next`, y puede ejecutar lógica tanto antes como después de esa llamada. Como ASP.NET Core conecta el enrutamiento al principio mismo del pipeline en cuanto hay un endpoint configurado, este bloque `app.Use` ya se ejecuta después de que la petición fue emparejada con el endpoint `/` — así que `next(context)` aquí lleva directo a la ejecución de ese endpoint, por eso se imprime "Before", luego el handler de `/` escribe "Hello", y luego se imprime "After" una vez que el control regresa. La opción de "se ejecuta una sola vez al arrancar" es incorrecta: el `app.Run()` que arranca el host, al final de `Program.cs`, no tiene relación con la sobrecarga de middleware terminal que también se llama `Run`, y este delegado de `app.Use` se ejecuta en cada petición que coincide, no una sola vez al arrancar. La opción que prohíbe ejecutar código después de `next` está al revés e inventa una comprobación del runtime que no existe — ejecutar código después de `await next(context)` es la forma normal y soportada de observar la respuesta en su camino de vuelta, y es exactamente lo que hace posible el middleware de logging/medición de tiempos; nada lanza una excepción por hacerlo. La opción que afirma que `app.Use` solo registra middleware que corre antes del enrutamiento también es incorrecta e inventa un "paso de registro aparte" que ASP.NET Core no tiene: el middleware registrado en cualquier parte del pipeline puede seguir ejecutando lógica después de que `next` retorna, es decir, después de que el endpoint ya escribió su respuesta — así funciona el middleware que inspecciona la respuesta (compresión, registro de códigos de estado, etcétera), sin que exista ningún segundo paso.',
    hint:
      'Sigue las dos llamadas a `Console.WriteLine` durante una sola petición y pregúntate qué representa el delegado `next`.',
  },
  'aspnet-controller-di-and-routing': {
    prompt:
      '```csharp\n[ApiController]\n[Route("api/[controller]")]\npublic class OrdersController : ControllerBase\n{\n    private readonly IOrderService _orders;\n\n    public OrdersController(IOrderService orders)\n    {\n        _orders = orders;\n    }\n\n    [HttpGet("{id}")]\n    public IActionResult GetById(int id)\n    {\n        var order = _orders.Find(id);\n        if (order is null)\n        {\n            return NotFound();\n        }\n        return Ok(order);\n    }\n}\n```\n¿Cuál afirmación describe correctamente este controlador?',
    options: {
      a: '`IOrderService orders` debe resolverse manualmente dentro del constructor:\n\n```csharp\n_orders = HttpContext.RequestServices.GetService<IOrderService>();\n```\nLos controladores de ASP.NET Core solo soportan inyección por propiedades, no por constructor',
      b: '`[ApiController]` es lo que hace que la ruta sea alcanzable; sin él, el enrutamiento ignora por completo `[HttpGet]`/`[Route]` y trata la clase como un objeto plano sin ruta',
      c: 'Como `GetById` devuelve `IActionResult`, la respuesta siempre se serializa como XML a menos que el cliente envíe explícitamente el encabezado `Accept: application/json` — JSON solo es un formato de reserva negociado',
      d: '`IOrderService orders` es entregado por DI cuando el controlador se activa, ya que `IOrderService` está registrado en `builder.Services`; `[Route("api/[controller]")]` más `[HttpGet("{id}")]` mapean a `GET /api/Orders/{id}`',
    },
    explanation:
      'La factoría de controladores de ASP.NET Core resuelve los parámetros del constructor desde el contenedor de DI cuando activa un controlador para una petición, exactamente igual que con cualquier otra clase gestionada por DI — no hace falta ninguna búsqueda manual con `HttpContext.RequestServices`, y la inyección por constructor es de hecho la forma estándar y recomendada de consumir servicios en un controlador, lo cual hace incorrecta la opción de buscar el servicio a mano con `RequestServices`. `[Route("api/[controller]")]` combinado con el enrutamiento por atributos en la acción produce `api/Orders/{id}`, que coincide con `[HttpGet("{id}")]` de `GetById`. La opción que dice que `[ApiController]` hace alcanzable la ruta exagera lo que hace: el enrutamiento por atributos y `[HttpGet]`/`[Route]` también funcionan en una clase `ControllerBase` normal; `[ApiController]` agrega comodidades encima (respuestas 400 automáticas para un model state inválido, inferencia de fuentes de binding y exigir enrutamiento por atributos), pero no determina si la ruta es alcanzable. La opción de "siempre se serializa como XML" es incorrecta porque JSON, no XML, es el formateador de salida por defecto (y normalmente el único) registrado en ASP.NET Core; un formateador XML solo participa en la negociación de contenido si se agrega explícitamente con `AddXmlSerializerFormatters()`.',
    hint:
      'Recuerda cómo activa la fábrica de controladores un controlador en cada petición, y cómo se combina el token `[controller]` con la plantilla de ruta del método.',
  },
  'aspnet-use-vs-run-mismatch': {
    prompt:
      '```csharp\napp.Use(async (context, next) =>\n{\n    if (context.Request.Path == "/health")\n    {\n        await context.Response.WriteAsync("OK");\n        return;\n    }\n    await next(context);\n});\n\napp.Run(async context =>\n{\n    await context.Response.WriteAsync("fallback");\n});\n\napp.MapGet("/hello", () => "hi");\n```\nUna petición a `GET /hello` devuelve `fallback` en lugar de `hi`. ¿Por qué, y cuál es la solución?',
    options: {
      a: '`app.Run` es **terminal** — nunca llama a `next`, así que siempre responde por sí mismo, y se ubica antes del `UseEndpoints` implícito, que siempre se conecta al final mismo del pipeline',
      b: '`app.Run` y `app.MapGet` no se pueden combinar en el mismo pipeline; el runtime lanza `InvalidOperationException` al arrancar a menos que cada llamada `Map*` sea la primera instrucción después de `app.Build()`, antes de cualquier `app.Use`',
      c: 'El bloque `app.Use` para `/health` es el error: su comparación de path se aplica en silencio a cualquier petición, incluida `/hello`, sin importar el `if` que se muestra en el código',
      d: 'Mover `app.MapGet("/hello", ...)` hasta arriba de `Program.cs`, antes de ambos bloques `app.Use`, lo soluciona: ASP.NET Core inserta el middleware implícito de ejecución de endpoint exactamente donde aparece la llamada `Map*` correspondiente',
    },
    explanation:
      'El middleware de `app.Use` recibe un delegado `next` y decide si lo llama; el middleware de `app.Run` no recibe ninguno — su firma es simplemente `(HttpContext) => Task`, así que por definición siempre produce una respuesta y nunca puede reenviar la petición. Una llamada a `Map*` como `app.MapGet` no inserta middleware en el pipeline en el punto donde se escribe — solo agrega una entrada al origen de datos de endpoints. En cuanto se configura cualquier endpoint, ASP.NET Core conecta implícitamente `UseRouting` al principio mismo del pipeline y `UseEndpoints` al final, envolviendo entre medio todo el middleware `app.Use`/`app.Run` escrito en `Program.cs`. Así que `/hello` ya está emparejado con un endpoint para cuando corre este código — pero para cualquier petición distinta de `/health`, el bloque `app.Use` condicional llama a `next`, entregando el control al `app.Run` incondicional, que se ubica antes del `UseEndpoints` implícito y, al ser terminal, nunca llama a `next` por sí mismo. `UseEndpoints` — y por lo tanto el handler real de `/hello` — nunca se alcanza. Solución: eliminar el `app.Run` que actúa como catch-all (un fallback real debería usar `app.MapFallback(...)`, que solo se ejecuta cuando ningún endpoint coincidió), o llamar a `UseRouting()`/`UseEndpoints()` explícitamente y colocar el `app.Run` terminal después de `UseEndpoints()`. La afirmación de que `app.Run` y `app.MapGet` no se pueden combinar es falsa e inventa una excepción de arranque que no existe — las llamadas a `Run` y a `Map*` se pueden intercalar libremente; solo importa el orden del middleware real respecto a la posición del `UseEndpoints` implícito. Culpar al bloque de `/health` es falso — el `if` sí limita correctamente la respuesta anticipada solo a `/health`. Mover `MapGet` al principio de `Program.cs` no arregla nada y es exactamente el instinto natural pero equivocado que esta trampa busca detectar: mover `MapGet` antes no cambia nada, porque las llamadas a `Map*` no participan en el orden del middleware — solo registran endpoints para que la maquinaria implícita de enrutamiento/ejecución los empareje e invoque después, y esa maquinaria siempre envuelve todo el conjunto de middleware de `Program.cs`, sin importar dónde se ubique cada llamada `Map*`.',
    hint:
      'Sigue una petición `GET /hello` por el pipeline en orden de registro, sin olvidar las piezas que agrega por ti el modelo de hosting mínimo.',
  },
  'aspnet-minimal-api-frombody-inference': {
    prompt:
      '```csharp\npublic record CreateOrderRequest(string CustomerId, List<string> ItemIds);\n\napp.MapPost("/orders", (CreateOrderRequest request, IOrderService orders) =>\n{\n    var id = orders.Create(request.CustomerId, request.ItemIds);\n    return Results.Created($"/orders/{id}", new { id });\n});\n```\n`IOrderService` está registrado en `builder.Services`. Un cliente hace un `POST` con este cuerpo de petición:\n\n```json\n{\n  "customerId": "c1",\n  "itemIds": ["i1"]\n}\n```\n¿Cómo se vinculan los dos parámetros?',
    options: {
      a: 'Ambos parámetros se vinculan desde el cuerpo: las minimal APIs deserializan el payload JSON de forma independiente en cada parámetro de tipo complejo, repartiendo las propiedades por nombre entre ellos',
      b: 'Las minimal APIs requieren un atributo `[FromBody]` explícito en `request`; sin él, el endpoint lanza `InvalidOperationException` al arrancar porque la fuente de binding para un parámetro `record` nunca puede inferirse',
      c: '`orders` se resuelve como servicio de DI porque `IOrderService` está registrado; `request` no coincide con ninguna otra fuente de binding, así que termina vinculándose desde el cuerpo JSON. Solo un parámetro puede vincularse implícitamente desde el cuerpo de esta forma',
      d: '`orders` se vincula desde el cuerpo porque se declara en segundo lugar en la lista de parámetros, y `request` se resuelve desde DI porque los tipos `record` siempre se tratan como servicios en el binding de minimal APIs, nunca se infieren de otra forma',
    },
    explanation:
      'El binding de parámetros de minimal APIs revisa, por cada parámetro, si coincide con una fuente conocida antes de recurrir al cuerpo: valores de ruta, cadena de consulta, atributos explícitos, tipos especiales del framework y — algo importante — si el tipo del parámetro está registrado como servicio en el contenedor de DI. `IOrderService` coincide con ese último caso, así que `orders` se resuelve desde el proveedor de servicios de la petición en lugar de parsearse desde el JSON. `request` no coincide con ninguna de esas fuentes (no hay un valor de ruta o de query llamado `request`, y `CreateOrderRequest` no es un servicio registrado), así que el framework lo trata como el parámetro implícito del cuerpo y deserializa el payload JSON en él. Solo un parámetro puede provenir del cuerpo de esta forma — un segundo tipo complejo sin atributo y sin otra fuente de binding produce un error de binding en tiempo de ejecución en lugar de repartirse entre ambos. La opción de "ambos parámetros se enlazan desde el body" inventa una regla de división de JSON por parámetro que ASP.NET Core no tiene. La opción que exige un `[FromBody]` explícito es incorrecta porque el atributo es opcional aquí precisamente porque la inferencia de fuente de binding ya lo resuelve correctamente, y no hay ninguna excepción en tiempo de arranque para este caso. La opción que enlaza `orders` desde el body y `request` desde DI inventa reglas de inferencia por posición y por ser un `record` que tampoco existen — la fuente de binding depende de dónde puede venir realmente el valor (ruta, query, DI, cuerpo), nunca del orden de los parámetros ni de que el tipo sea un `record`.',
    hint:
      'Recuerda el orden en que las minimal APIs infieren la fuente de binding de un parámetro que no tiene atributo.',
  },
  'aspnet-401-vs-403-policy': {
    prompt:
      '```csharp\n[Authorize(Policy = "CanEditOrders")]\n[HttpPut("{id}")]\npublic IActionResult Update(int id, OrderDto dto) { /* ... */ }\n```\nLa app registra JWT bearer como su esquema de autenticación por defecto, sin ningún esquema de cookies ni otro basado en redirección. El cliente A llama a este endpoint sin ningún encabezado `Authorization`. El cliente B lo llama con un token JWT bearer válido y correctamente firmado, de un usuario real que simplemente no cumple la política `CanEditOrders`. ¿Qué código de estado recibe cada uno, y por qué?',
    options: {
      a: 'Ambos clientes reciben `401 Unauthorized`; `[Authorize(Policy = ...)]` no puede distinguir "sin ninguna identidad" de "identidad presente pero política fallida" — ambos fallos producen el mismo código de estado, sin ninguna distinción',
      b: 'El cliente A recibe `401 Unauthorized` — no se pudo establecer ninguna identidad, lo cual dispara un "challenge". El cliente B recibe `403 Forbidden` — la autenticación tiene éxito, pero la política `CanEditOrders` falla contra ese principal',
      c: 'El cliente A recibe `403 Forbidden` (la falta de credenciales se trata como una denegación de acceso) y el cliente B recibe `401 Unauthorized` (un usuario autenticado que falla una política se trata como si nunca se hubiera autenticado)',
      d: 'Ambos clientes reciben `500 Internal Server Error`, porque la evaluación de la política se ejecuta antes que la autenticación en el pipeline, así que `HttpContext.User` todavía no existe cuando se comprueba la política `CanEditOrders` contra él',
    },
    explanation:
      'La autenticación y la autorización son dos modos de fallo distintos con dos respuestas distintas. Como JWT bearer es aquí el esquema por defecto de la app, sin alternativa interactiva, una credencial ausente o inválida produce un "challenge" de `401`, mientras que una credencial válida que falla la política `CanEditOrders` produce un "forbid" de `403` — el servidor sabe exactamente quién está preguntando y se niega a propósito, lo cual es una situación materialmente distinta de "no sé quién es esto". La opción de "ambos reciben `401`" colapsa esa distinción en un solo código de estado, y la de "A recibe `403`, B recibe `401`" la invierte. La opción del `500 Internal Server Error` es incorrecta porque `UseAuthentication` se ejecuta, y llena `HttpContext.User`, antes de que `UseAuthorization` evalúe cualquier atributo `[Authorize]` — aquí no hay excepción alguna, solo dos resultados distintos y bien definidos.',
    hint:
      'Para cada cliente, averigua hasta dónde llega la petición en la autenticación y la autorización, y qué devuelve cada etapa cuando falla.',
  },
  'aspnet-middleware-pipeline-tradeoffs': {
    prompt: '¿Qué afirmaciones sobre el pipeline de middleware de ASP.NET Core, el enrutamiento por endpoints y el manejo de excepciones son correctas? Selecciona todas las que apliquen.',
    options: {
      a: '`UseAuthentication` debe registrarse antes que `UseAuthorization`, porque el middleware de autorización lee `HttpContext.User`, que es responsabilidad del middleware de autenticación llenar; registrarlos en el orden inverso hace que la autorización evalúe contra un principal no autenticado, al menos para las políticas que no nombran `AuthenticationSchemes` explícitos',
      b: 'En el modelo de hosting minimalista, en cuanto se configura cualquier endpoint, `WebApplication` conecta implícitamente `UseRouting` al principio mismo del pipeline y `UseEndpoints` al final, envolviendo todo el middleware `app.Use`/`app.Run` registrado en `Program.cs` — las llamadas a `Map*`/`MapControllers` solo agregan entradas al origen de datos de endpoints, no cambian dónde se ubica ese middleware. Así que el middleware en cualquier parte de `Program.cs` sigue ejecutándose antes de que el endpoint emparejado realmente se ejecute, sin importar si se escribió antes o después de la llamada `Map*` correspondiente, a menos que un middleware terminal o que corta el pipeline intercepte la petición primero',
      c: '`UseExceptionHandler`, registrado cerca del inicio del pipeline, puede capturar excepciones no controladas lanzadas por cualquier componente posterior — enrutamiento, autenticación, autorización, middleware personalizado y ejecución de acciones de MVC por igual — mientras que un *filtro* de excepciones de MVC solo observa excepciones lanzadas durante el model binding, los filtros de acción y el método de acción, y nunca ve una excepción lanzada por middleware que se ejecuta antes o después de esa maquinaria, ni una lanzada por un filtro de resultado',
      d: 'Los filtros de excepciones ven las excepciones lanzadas por cualquier middleware anterior en el pipeline, no solo las que se generan durante la ejecución de la acción, porque los filtros de MVC envuelven todo el pipeline de la petición y no solo la acción del controlador',
      e: "Un middleware que nunca llama a `next()` (o `next.Invoke()`) corta el pipeline en seco: nada de lo registrado después de él — ni siquiera la ejecución de un endpoint que coincida — se ejecuta para esa petición",
    },
    explanation:
      'El orden del pipeline no es una preferencia de estilo en ASP.NET Core; varios componentes dependen estrictamente de lo que se ejecutó antes que ellos. `UseAuthorization` inspecciona `HttpContext.User`, que — para una política que no nombra `AuthenticationSchemes` explícitos — solo tiene una identidad porque `UseAuthentication` se ejecutó primero y la llenó a partir de las credenciales de la petición; invertir el orden para esa política hace que cada verificación `[Authorize]` evalúe contra un principal anónimo, sin importar cuán válido sea en realidad el token del llamador. (Una política que sí nombra esquemas específicos es una excepción más acotada: el evaluador de políticas del middleware de autorización puede disparar la autenticación de esos esquemas por sí mismo, pero eso no es la regla general.) El enrutamiento por endpoints se conecta de la misma forma aunque sea implícito: en cuanto se configura cualquier endpoint, `WebApplication` inserta `UseRouting` al principio mismo del pipeline y `UseEndpoints` al final, envolviendo todo el middleware `app.Use`/`app.Run` escrito en `Program.cs` — las llamadas a `Map*`/`MapControllers` solo agregan entradas al origen de datos de endpoints, no cambian dónde se ubica ese middleware. Así que el emparejamiento de rutas ocurre antes de todo el middleware del usuario, y el endpoint emparejado solo se ejecuta realmente después de todo eso, a menos que un middleware terminal o que corta el pipeline — el mismo mecanismo que la opción del middleware que corta el pipeline — intercepte la petición primero. El middleware `UseExceptionHandler` se ubica en el pipeline como cualquier otro middleware, así que si está lo bastante temprano, envuelve y puede capturar excepciones de todo lo que está después de él, incluido MVC; un filtro de excepciones de MVC, en cambio, solo observa excepciones lanzadas durante el model binding, los filtros de acción o el método de acción mismo, así que no puede ver una excepción lanzada por el enrutamiento, la autenticación, un middleware personalizado o incluso un filtro de resultado — que es exactamente lo que hace falsa la afirmación de que los filtros de excepción ven las excepciones del middleware anterior, y verdadera la de `UseExceptionHandler`.\n\n**Dilo en voz alta:** "`UseAuthentication` tiene que ejecutarse antes que `UseAuthorization`, y el endpoint emparejado solo se ejecuta realmente al final del pipeline, no donde sea que esté escrito `Map*`. Un middleware que corta el pipeline en cualquier punto anterior puede absorber la petición, y un filtro de excepciones solo ve lo que pasa dentro del propio código de invocación de acciones de MVC, nunca nada anterior en el pipeline."',
    hint:
      'Recorre el pipeline en orden: quién llena `HttpContext.User`, qué agrega implícitamente el modelo de hosting mínimo y dónde se ubica cada mecanismo de manejo de excepciones.',
  },
  'aspnet-minimal-api-vs-controllers-tradeoffs': {
    prompt:
      'Tu equipo va a agregar una nueva superficie HTTP de lectura/escritura para recursos `Order` en una app de .NET 8/9 que ya aloja varios controladores MVC bien establecidos. Discute las ventajas y desventajas entre construir los nuevos endpoints como minimal APIs (`MapGet`/`MapPost` sobre `WebApplication`) o como un controlador MVC, cómo moldearías las respuestas de la minimal API usando `IResult`/`TypedResults` si eligieras ese camino, y por qué agregarías un parámetro `CancellationToken` a los handlers en cualquiera de los dos casos.',
    modelAnswer:
      'Las minimal APIs y los controladores terminan ambos despachando a un método de C# a través del enrutamiento, pero difieren en la sobrecarga y en cuánta estructura obtienes gratis. Las minimal APIs se saltan el pipeline de filtros de MVC y la maquinaria de activación de controladores, así que hay menos indirección por petición y menos boilerplate para un conjunto de endpoints pequeño y enfocado — pero eso también significa que se pierden cosas que `[ApiController]` da gratis a los controladores, sobre todo: sin trabajo extra, los handlers de minimal API no ejecutan automáticamente la validación de DataAnnotations sobre un modelo vinculado ni cortan con un `400 ValidationProblemDetails` como sí hace un controlador decorado con `[ApiController]`, así que la validación hay que hacerla explícitamente (dentro del handler o mediante un filtro agregado). Los controladores también traen el pipeline completo de filtros de acción/excepción/resultado, que es valioso cuando el comportamiento transversal (logging, caché, validación, verificaciones de autorización que necesitan correr en una etapa específica) ya está expresado como filtros en el resto de la app — reutilizar eso de forma consistente es un argumento real para quedarse con controladores en una base de código que ya tiene varios, solo por consistencia e infraestructura compartida, aunque una superficie nueva y aislada funcionaría igual de bien como minimal APIs. Si optara por minimal APIs, seguiría llamando a `TypedResults` dentro del handler (por ejemplo, `TypedResults.Ok(order)`, `TypedResults.NotFound()`), pero también declararía el tipo de retorno del handler como el tipo tipado concreto — `Ok<Order>` para un solo resultado posible, o la unión `Results<Ok<Order>, NotFound>` cuando el handler puede producir más de un resultado — en lugar de anotarlo como la interfaz genérica `IResult`. Declarar el tipo de retorno como `IResult` a secas borra esa información de tipo en tiempo de compilación, lo cual hace perder dos cosas: el handler se vuelve más difícil de probar unitariamente (solo se puede verificar la respuesta escrita en un `HttpContext` falso, no un resultado concreto y su `Value`) y, más importante, se pierden metadatos de respuesta OpenAPI precisos, que el framework solo puede inferir de una firma que realmente nombre los tipos de resultado concretos o su unión, no de llamadas a `.Produces<Order>()` agregadas después como parche. En cualquiera de los dos casos — minimal API o controlador — agregaría un parámetro `CancellationToken` al handler/acción; ASP.NET Core lo vincula automáticamente a `HttpContext.RequestAborted`, y pasarlo a la consulta de EF Core o a la llamada posterior de `HttpClient` permite que ese trabajo realmente se detenga cuando el llamador se desconecta, en lugar de que el servidor siga reteniendo una conexión a la base de datos y haciendo trabajo para una respuesta que nadie va a recibir jamás.',
    rubric: [
      'Indica al menos un costo concreto de las minimal APIs respecto a los controladores (por ejemplo, no hay validación automática de DataAnnotations ni corte de model-state como el que da [ApiController]) y al menos un beneficio concreto (menos overhead/boilerplate, o ausencia del pipeline de filtros de MVC)',
      'Indica al menos una razón concreta para preferir controladores en este caso específico, vinculada a los controladores MVC ya existentes en la app (filtros/convenciones/consistencia compartidos), en lugar de declarar un enfoque universalmente mejor',
      'Indica que un handler debe declarar su tipo de retorno como un tipo concreto de TypedResults (por ejemplo, Ok<Order>) o una unión Results<...>, no la interfaz IResult a secas, porque declarar IResult borra la información de tipo de la que dependen la inferencia de metadatos OpenAPI y las aserciones más fuertes en pruebas unitarias',
      'Indica que un parámetro CancellationToken en el handler se vincula a HttpContext.RequestAborted y explica por qué importa propagarlo a las llamadas asíncronas posteriores (evitar trabajo/conexiones de base de datos desperdiciados cuando el cliente se desconecta)',
      'Aplica el razonamiento tanto a minimal APIs como a controladores, en lugar de tratar el CancellationToken o la discusión de ventajas y desventajas como específicos de uno solo de los dos',
    ],
    explanation:
      'Esta pregunta deliberadamente no busca "las minimal APIs son más rápidas" como toda la respuesta — la parte interesante es reconocer que perder la validación automática de `[ApiController]` es un costo real, que un handler tiene que declarar realmente un tipo de retorno concreto de `TypedResults` (no solo llamar a `TypedResults.*` mientras sigue tipado como `IResult`) para conservar la precisión de OpenAPI y la capacidad de pruebas, y que el punto del CancellationToken aplica de forma uniforme sin importar qué estilo de hosting gane.\n\n**Dilo en voz alta:** "Las minimal APIs te cuestan la validación automática de model-state y el pipeline de filtros que dan los controladores con `[ApiController]`, así que en una base de código que ya se apoya en controladores mantendría la consistencia. Si usara minimal APIs declararía tipos de retorno concretos de `TypedResults` por capacidad de pruebas y metadatos OpenAPI precisos, y en cualquier caso aceptaría un `CancellationToken` para que las peticiones abandonadas dejen de trabajar en lugar de completarse para nadie."',
    hint:
      'Sopesa lo que `[ApiController]` te da gratis, cómo ayudan los tipos de retorno concretos de `TypedResults` a OpenAPI y a las pruebas, y qué hace un `CancellationToken` cuando el cliente se desconecta.',
  },
  'aspnet-jwt-bearer-policy-authorization': {
    prompt:
      'Diseña la autorización para `PUT /orders/{id}` de forma que solo el dueño de la orden, o un usuario con el rol `OrdersManager`, pueda actualizarla. Explica cómo valida ASP.NET Core el token JWT bearer entrante en primer lugar, luego explica por qué un simple `[Authorize(Roles = "OrdersManager")]` no basta por sí solo para esta regla, y qué agrega un requirement/handler personalizado que una verificación de rol por sí sola no puede.',
    modelAnswer:
      'La validación del JWT bearer se configura mediante `AddAuthentication(...).AddJwtBearer(options => options.TokenValidationParameters = new TokenValidationParameters { ValidateIssuer = true, ValidIssuer = ..., ValidateAudience = true, ValidAudience = ..., ValidateLifetime = true, ValidateIssuerSigningKey = true, IssuerSigningKey = ... })`. En cada petición, el handler de JWT bearer verifica la firma del token contra la clave de firma configurada, y verifica el emisor, la audiencia y la expiración contra esos `TokenValidationParameters`; si todas las comprobaciones pasan, construye un `ClaimsPrincipal` a partir de los claims del token y lo asigna a `HttpContext.User` (esto solo surte efecto para el middleware posterior porque `UseAuthentication` se ejecuta antes que `UseAuthorization`). `[Authorize(Roles = "OrdersManager")]` por sí solo puede expresar la rama de "manager" de la regla, pero no puede expresar "o es el dueño de esta orden específica", porque una verificación de rol solo mira los claims que ya están presentes en el principal — no tiene forma de comparar esos claims contra la `Order` específica que se está actualizando, ya que el atributo se evalúa antes de que el recurso siquiera se cargue. Para combinar ambas ramas, definiría un `IAuthorizationRequirement` personalizado (por ejemplo, `SameOwnerOrRoleRequirement`) y un `AuthorizationHandler<SameOwnerOrRoleRequirement, Order>` tipado por recurso, cuyo `HandleRequirementAsync` cumple el requirement si `context.User.IsInRole("OrdersManager")` es verdadero, o si el id del dueño de la orden coincide con un claim de id en `context.User`. Lo registraría con `services.AddAuthorization(options => options.AddPolicy("CanEditOrder", policy => policy.Requirements.Add(new SameOwnerOrRoleRequirement())))` y `services.AddSingleton<IAuthorizationHandler, SameOwnerOrRoleHandler>()`. Como esto es autorización basada en recurso — la decisión depende de la `Order` específica, no solo de los claims del llamador — no puede expresarse por completo con un atributo `[Authorize]` declarativo en la acción; en su lugar, la acción carga primero la orden, luego llama a `await _authorizationService.AuthorizeAsync(User, order, "CanEditOrder")` y devuelve `Forbid()` (403) si eso falla.',
    rubric: [
      'Describe la validación de JWT bearer mediante TokenValidationParameters (emisor, audiencia, expiración, clave de firma) e indica que el éxito llena HttpContext.User con claims para el middleware posterior',
      'Indica que una verificación de rol por sí sola no puede expresar la propiedad de un recurso específico porque solo inspecciona claims ya presentes en el principal, no la entidad sobre la que se actúa',
      'Describe definir un IAuthorizationRequirement personalizado más un AuthorizationHandler<TRequirement> (idealmente tipado por recurso) registrado mediante AddPolicy/AddAuthorization',
      'Indica que la autorización basada en recurso requiere una llamada imperativa a IAuthorizationService.AuthorizeAsync(user, resource, policy) después de cargar la entidad, ya que un atributo [Authorize] declarativo se ejecuta antes de que el recurso exista',
      'Produce una regla combinada coherente (rol OrdersManager O coincidencia de propiedad) en lugar de cubrir solo una de las dos ramas',
    ],
    explanation:
      'La trampa de este escenario es detenerse en `[Authorize(Roles = "OrdersManager")]` y no notar que eso descarta por completo, en silencio, la rama de propiedad de la regla, porque una verificación de rol declarativa no tiene forma de ver el recurso que se está modificando — se ejecuta, y termina, antes de que la acción siquiera cargue la `Order`.\n\n**Dilo en voz alta:** "Un atributo de rol puede expresar la rama de manager, pero no la propiedad de esta orden específica, porque nunca ve el recurso. Así que agregaría un requirement y un handler basados en recurso, lo registraría como política, y llamaría a `AuthorizeAsync` contra la orden una vez cargada, en lugar de forzar todo en un solo atributo."',
    hint:
      'Explica qué valida el handler de bearer (firma, emisor, audiencia, vigencia) y luego por qué la propiedad necesita el propio recurso: piensa en autorización basada en recursos con `IAuthorizationService`.',
  },
};
