// engine
import type { QuestionTranslation } from '../../engine/question';

export const translations: Record<string, QuestionTranslation> = {
  'dotnet-service-lifetime-basics': {
    prompt:
      'Un host construido con `Host.CreateApplicationBuilder` registra servicios con `AddSingleton`, `AddScoped` y `AddTransient`. ¿Cuál afirmación describe correctamente estos tres lifetimes?',
    options: {
      a: 'Singleton: una sola instancia durante toda la vida de la aplicación; Scoped: una instancia por scope (por petición HTTP en ASP.NET Core, o por cada `IServiceScope` creado explícitamente en otro tipo de host); Transient: una instancia nueva cada vez que se resuelve',
      b: 'Singleton: una instancia por petición; Scoped: una instancia durante toda la vida de la aplicación; Transient: una instancia por scope',
      c: 'Transient: una instancia durante toda la vida de la aplicación; Scoped: se crea una vez y se guarda en caché para siempre después de la primera resolución; Singleton: una instancia nueva en cada inyección',
      d: 'Los tres lifetimes se comportan igual fuera de ASP.NET Core; la distinción solo importa cuando un servidor web está atendiendo peticiones',
    },
    explanation:
      'Un singleton se crea una vez (la primera vez que se solicita, salvo que se registre como una instancia ya existente) y esa misma instancia se entrega a todos los consumidores durante toda la vida de la app. Un servicio scoped obtiene una instancia por scope: ASP.NET Core crea un scope automáticamente por cada petición HTTP entrante, y cualquier otro tipo de host (app de consola, worker, job en segundo plano) tiene que crear los scopes de forma explícita para lograr el mismo comportamiento. Un servicio transient se construye desde cero cada vez que se resuelve, incluso más de una vez dentro del mismo grafo de objetos. Las dos opciones que revuelven las definiciones de singleton, scoped y transient simplemente las intercambian. La opción que afirma que los tiempos de vida se comportan igual fuera de ASP.NET Core es incorrecta porque el límite de scope existe en cualquier host que cree `IServiceScope`s, no solo en peticiones web — un `BackgroundService` que procesa mensajes de una cola, por ejemplo, típicamente crea un scope por mensaje.',
    hint:
      'Piensa en qué es un scope en ASP.NET Core frente a un host de consola o worker, y en cada cuánto entrega una instancia nueva cada registro.',
  },
  'dotnet-dbset-basics': {
    prompt:
      "```csharp\npublic class AppDbContext : DbContext\n{\n    public DbSet<Product> Products { get; set; }\n}\n```\n¿Qué representa la propiedad `DbSet<Product> Products`?",
    options: {
      a: 'Una colección consultable y rastreable que representa la tabla (o vista) `Products` mapeada a `Product`; se usa tanto para construir consultas LINQ traducidas a SQL como para agregar, quitar o actualizar instancias rastreadas de `Product`',
      b: 'Una lista en memoria y en caché de cada fila de `Product`, cargada de forma anticipada en el momento en que se construye `AppDbContext`',
      c: 'Un singleton estático y thread-safe compartido por todas las instancias de `AppDbContext` en el proceso',
      d: 'Una vista de solo lectura: las entidades modificadas a través del `DbSet` nunca se persisten, y `SaveChanges` solo persiste SQL escrito a mano',
    },
    explanation:
      "`DbSet<T>` implementa `IQueryable<T>`, así que el LINQ escrito contra él se traduce a SQL y se ejecuta solo cuando la consulta se enumera — nada se carga de forma anticipada en el momento de la construcción, lo cual descarta la opción de la \"lista en memoria cacheada\". Pertenece a una sola instancia de `DbContext`; no es un objeto estático compartido ni thread-safe — el propio `DbContext` no es seguro de usar desde varios hilos a la vez — lo cual descarta la opción del \"singleton estático y thread-safe\". Las entidades agregadas, modificadas o eliminadas a través del `DbSet` (o cargadas y mutadas mientras están rastreadas) son exactamente lo que `SaveChanges`/`SaveChangesAsync` persiste como sentencias `INSERT`/`UPDATE`/`DELETE`, así que la opción de la \"vista de solo lectura\" está al revés.",
    hint:
      'Recuerda para qué usa EF Core un `DbSet<T>`, tanto al leer datos como al guardar cambios.',
  },
  'dotnet-configuration-provider-precedence': {
    prompt:
      'Un host se construye con el pipeline de configuración por defecto de `Host.CreateApplicationBuilder(args)`. La clave `ConnectionStrings:Default` está definida en `appsettings.json`, de nuevo en `appsettings.Development.json`, como la variable de entorno `ConnectionStrings__Default`, y como el argumento de línea de comandos `--ConnectionStrings:Default=...`. ¿Qué devuelve `configuration["ConnectionStrings:Default"]`?',
    options: {
      a: 'El valor de línea de comandos, porque los argumentos de línea de comandos son el último proveedor agregado, y para una clave dada, un proveedor posterior sobrescribe a uno anterior',
      b: 'El valor de la variable de entorno, porque las variables de entorno siempre tienen prioridad sobre cualquier otra fuente de configuración por razones de seguridad',
      c: 'El valor de `appsettings.json`, porque la configuración basada en archivos se carga primero y se considera la fuente autoritativa',
      d: 'Lanza `InvalidOperationException` al arrancar, porque la misma clave está definida por más de un proveedor',
    },
    explanation:
      '`IConfiguration` combina todos los proveedores en una sola vista plana de clave/valor en el orden de registro; para una clave presente en más de un proveedor, gana el que se haya agregado más tarde. Con el orden por defecto usado aquí, los argumentos de línea de comandos se agregan después de las variables de entorno, que a su vez se agregan después de los archivos JSON, así que gana el valor de línea de comandos. (El doble guion bajo en `ConnectionStrings__Default` es la forma en que las variables de entorno representan el separador de sección `:`, ya que los dos puntos son incómodos o inválidos en la mayoría de los shells y nombres de variables de entorno del sistema operativo). No hay nada relacionado con seguridad en la prioridad de las variables de entorno, y la configuración nunca lanza una excepción cuando la misma clave está definida por más de un *proveedor* — simplemente toma el último valor en silencio, que es exactamente el tipo de cosa que vale la pena revisar cuando un ajuste "no está teniendo efecto" (una clave duplicada dentro del propio objeto de un mismo archivo JSON es un caso distinto: eso sí lanza `FormatException` al cargar el archivo).',
    hint:
      'Recuerda cómo resuelve `IConfiguration` una clave definida por varios providers, y en qué orden los agrega el builder por defecto.',
  },
  'dotnet-addscoped-console-host': {
    prompt:
      "```csharp\nvar builder = Host.CreateApplicationBuilder(args);\nbuilder.Services.AddDbContext<AppDbContext>(o => o.UseSqlServer(connStr));\nbuilder.Services.AddScoped<IOrderProcessor, OrderProcessor>();\n\nvar app = builder.Build();\n\nvar processor = app.Services.GetRequiredService<IOrderProcessor>();\nforeach (var message in queue.ReadAllMessages())\n{\n    processor.Process(message);\n}\n```\nEste es un host de consola/worker sin pipeline de peticiones HTTP; `processor` se resuelve una sola vez y luego se reutiliza para cada mensaje del bucle. ¿Por qué resolver `IOrderProcessor` directamente desde `app.Services` aquí es un error, y cuál es la solución?",
    options: {
      a: '`app.Services` es el proveedor de servicios **raíz**. Un servicio scoped resuelto desde ahí queda capturado, en la práctica, como un singleton durante toda la vida de la aplicación — se reutiliza una sola instancia en cada llamada y nunca se libera hasta el apagado, y cualquier dependencia scoped dentro de él (como un `AppDbContext` scoped) queda capturada de la misma forma, produciendo estado compartido y no thread-safe. Solución: crear un scope explícito por unidad de trabajo con `app.Services.CreateScope()` (o un `IServiceScopeFactory` inyectado), resolver `IOrderProcessor` desde `scope.ServiceProvider` y liberar el scope cuando esa unidad de trabajo termine',
      b: 'No es un error: fuera de una petición web no hay ningún límite de scope, así que `AddScoped` se comporta exactamente igual que `AddSingleton`, que es el comportamiento deseado en un host de consola',
      c: 'No es un error: `IServiceProvider.GetRequiredService` siempre abre y descarta un scope nuevo internamente en cada llamada, así que se crea un `IOrderProcessor` nuevo (y un `AppDbContext` interno nuevo) cada vez que se ejecuta `Process()`',
      d: '`AddScoped` no se puede registrar en absoluto en un host de consola; llamarlo lanza una excepción al arrancar a menos que también se llame a `builder.Services.AddHttpContextAccessor()`',
    },
    explanation:
      'No existe un scope automático por petición en un host de consola o worker, así que alguien tiene que crear los scopes a propósito — el framework no lo hace por ti como sí lo hace con una petición HTTP entrante. `Host.CreateApplicationBuilder` habilita `ValidateScopes` y `ValidateOnBuild` cuando el entorno del host es Development, así que en Development este fragmento lanza "`InvalidOperationException: Cannot resolve scoped service \'IOrderProcessor\' from root provider`" en el momento en que se ejecuta `GetRequiredService<IOrderProcessor>()`. Un host de consola usa por defecto el entorno `Production` a menos que se defina `DOTNET_ENVIRONMENT` (o `ASPNETCORE_ENVIRONMENT`), así que por defecto — en Production — esa validación está desactivada y la llamada tiene éxito en silencio: `processor` se resuelve una sola vez desde el proveedor raíz y luego se reutiliza para cada mensaje del bucle, junto con cualquier dependencia scoped capturada dentro de él (como un `AppDbContext` scoped), que es exactamente el bug de entidades rastreadas obsoletas y reutilización no thread-safe del que trata esta pregunta. La solución es la misma en cualquier caso: crear un scope por operación lógica — `app.Services.CreateScope()` en un script simple, o `IServiceScopeFactory.CreateScope()` inyectado en una clase como un `BackgroundService` — y resolver los servicios scoped desde `scope.ServiceProvider`, liberando el scope cuando la operación termina.',
    hint:
      'Recuerda de dónde salen los scopes en un host de .NET, y qué pasa cuando resuelves un servicio scoped fuera de uno.',
  },
  'dotnet-ef-executionstrategy': {
    prompt:
      "```csharp\nbuilder.Services.AddDbContext<AppDbContext>(o =>\n    o.UseSqlServer(connStr, sql => sql.EnableRetryOnFailure()));\n\n// más adelante\nusing var tx = await db.Database.BeginTransactionAsync();\ndb.Orders.Add(order);\nawait db.SaveChangesAsync();\nawait tx.CommitAsync();\n```\n`EnableRetryOnFailure` configura una `IExecutionStrategy` con reintentos. Este código lanza `InvalidOperationException: The configured execution strategy ... does not support user-initiated transactions.` ¿Por qué, y cuál es la solución?",
    options: {
      a: 'Una execution strategy con reintentos reintenta toda una unidad de trabajo cuando ocurre un fallo transitorio. Una transacción abierta manualmente que abarca varias llamadas, de otro modo, se reintentaría solo a medias, dejándola confirmada, revertida o re-ejecutada de forma inconsistente, así que EF Core se niega a mezclar una strategy con reintentos con una transacción gestionada por el usuario. Solución: dejar que la strategy sea la dueña del límite de la transacción, abriendo, guardando y confirmando la transacción dentro de `strategy.ExecuteAsync(...)`, donde `strategy` viene de `db.Database.CreateExecutionStrategy()`',
      b: '`BeginTransactionAsync` solo funciona contra SQLite; en SQL Server, las transacciones siempre deben iniciarse con `System.Transactions.TransactionScope`',
      c: '`EnableRetryOnFailure` deshabilita las transacciones por completo, así que `SaveChangesAsync` ya confirma cada cambio de forma independiente y la transacción explícita hay que eliminarla en lugar de envolverla',
      d: 'La excepción significa que a la cadena de conexión le falta `MultipleActiveResultSets=true`; agregarlo resuelve el conflicto entre la política de reintentos y la transacción',
    },
    explanation:
      'Este es uno de los mensajes de error más claros que produce EF Core, y apunta a un problema de corrección real, no solo a una preferencia de estilo: reintentar una consulta o una llamada a `SaveChanges` de forma transparente solo es seguro si el reintento puede rehacer *toda* la operación limpiamente, y una transacción que se abrió fuera de la strategy no se puede rebobinar y repetir de forma segura por ella. La solución es mover la transacción dentro del delegado de la strategy — ya sea `strategy.ExecuteAsync(async () => { await using var tx = await db.Database.BeginTransactionAsync(); db.Orders.Add(order); await db.SaveChangesAsync(); await tx.CommitAsync(); })`, o la extensión `ExecuteInTransactionAsync(operation, verifySucceeded)` construida justo para este patrón — en cualquiera de los dos casos, `strategy` (obtenida con `db.Database.CreateExecutionStrategy()`) pasa a ser responsable de iniciar y confirmar la transacción, así que un reintento reinicia toda la unidad de trabajo desde cero. La opción de "solo funciona con SQLite" es falsa — `BeginTransactionAsync` también es la forma normal de iniciar una transacción en SQL Server. La opción de "desactiva las transacciones por completo" es falsa — `EnableRetryOnFailure` no impide que `SaveChangesAsync` envuelva sus propias sentencias en una transacción (implícita); solo agrega una strategy con reintentos alrededor de toda la operación, y una transacción abierta manualmente que abarca varias llamadas igual tiene que vivir dentro del delegado de esa strategy, no alrededor de ella. La opción de `MultipleActiveResultSets=true` no tiene relación: MARS afecta la ejecución de varios result sets de forma concurrente en una misma conexión y no tiene nada que ver con esta excepción.',
    hint:
      'Pregúntate qué tiene que volver a ejecutar una estrategia de ejecución con reintentos cuando un fallo transitorio ocurre a mitad de este código.',
  },
  'dotnet-di-lifetime-pitfalls': {
    prompt: '¿Qué afirmaciones sobre los lifetimes de DI, las captive dependencies y `IHostedService`/`BackgroundService` en .NET son correctas? Selecciona todas las que apliquen.',
    options: {
      a: 'Un servicio singleton que recibe un servicio scoped como dependencia de constructor es una "captive dependency": la instancia scoped queda capturada durante toda la vida del singleton en lugar de recrearse por scope, lo cual anula el propósito de registrarla como scoped',
      b: 'Con el proveedor de servicios por defecto, habilitar la validación de scope junto con `ValidateOnBuild` (como hacen por defecto el generic host y `WebApplicationBuilder` en el entorno Development) puede detectar una captive dependency de singleton-depende-de-scoped al arrancar, cuando se construye el proveedor, en lugar de solo detectarla en el primer uso en producción',
      c: 'Un `BackgroundService`/`IHostedService` se registra y se resuelve como singleton, así que si su trabajo necesita un servicio scoped como `AppDbContext`, debería inyectar `IServiceScopeFactory` y crear un scope nuevo por unidad de trabajo dentro de `ExecuteAsync`, en lugar de inyectar el servicio scoped directamente en su constructor',
      d: 'Inyectar `IServiceProvider` en una clase y llamar a `GetService` directamente sobre él cada vez que se necesita una dependencia scoped (el patrón "service locator") es la forma recomendada por defecto de consumir servicios scoped desde un singleton, porque evita por completo las captive dependencies',
      e: 'Un servicio transient inyectado en un singleton sigue siendo retenido por ese singleton durante todo el tiempo que este viva; "transient" solo garantiza una instancia nueva en el momento en que se resuelve, no que cada uso de ella sea de corta duración',
    },
    explanation:
      'Una captive dependency ocurre puramente por la *forma* del grafo del constructor: nada impide inyectar un servicio scoped en un singleton, así que el contenedor de DI tiene que capturarlo (silenciosamente incorrecto) o rechazarlo (validado). La validación de scope/build existe precisamente para convertir la versión silenciosa en una ruidosa durante el arranque, en lugar de un bug sutil que aparece bajo carga. Un `BackgroundService` nunca recibe un scope entregado — se construye una sola vez, como singleton, así que cualquier trabajo scoped tiene que abrir su propio scope, típicamente una vez por iteración del bucle o por mensaje: `using var scope = _scopeFactory.CreateScope(); var db = scope.ServiceProvider.GetRequiredService<AppDbContext>();`. Inyectar `IServiceProvider` y llamar a `GetService` directamente es el antipatrón de *service locator*: dejando de lado que oculta las dependencias reales del constructor, llamar a `GetService` sobre el proveedor entregado a un singleton sin crear antes un scope resuelve los servicios scoped desde el proveedor raíz, que es exactamente el mismo problema de captive dependency/resolución inválida del que trata esta pregunta — la herramienta correcta es `IServiceScopeFactory.CreateScope()`, no una referencia directa al proveedor. Transient solo significa "instancia nueva por llamada a resolución"; una vez que un objeto de vida más larga guarda una referencia a ella, esa referencia vive exactamente tanto como su dueño, lo cual es una fuente común de sorpresas del tipo "los servicios transient no son realmente transient".\n\n**Dilo en voz alta:** "Las captive dependencies vienen de la forma del grafo del constructor, no de un error de tipeo, así que me apoyo en la validación de scope del proveedor para detectar un singleton que arrastra un servicio scoped al arrancar, y dentro de un `BackgroundService` siempre creo un scope explícito por unidad de trabajo en lugar de inyectar servicios scoped o recurrir al service locator."',
    hint:
      'Contrasta cada afirmación con lo que es una dependencia cautiva, lo que revisa la validación de scopes al construir el proveedor, cómo se registran los hosted services y lo que recomienda Microsoft para el trabajo scoped.',
  },
  'dotnet-ioptions-variants': {
    prompt:
      'Un servicio lee una sección `SmtpOptions` vinculada desde la configuración. Compara `IOptions<SmtpOptions>`, `IOptionsSnapshot<SmtpOptions>` e `IOptionsMonitor<SmtpOptions>`: ¿cuándo usas cada uno, y cuáles son los trade-offs de lifetime y de recarga de cambios?',
    modelAnswer:
      "`IOptions<T>` e `IOptionsMonitor<T>` se registran ambos como singletons, así que los dos son seguros de inyectar directamente en otro singleton sin crear un problema de captive dependency; `IOptionsSnapshot<T>`, el único de los tres registrado como scoped, es el que no lo es. `IOptions<T>` vincula sus opciones la primera vez que se acceden y nunca las vuelve a leer después, así que se entregan los mismos valores durante el resto de la vida de la app y nunca refleja una recarga posterior de la configuración — eso lo hace el más simple y económico de los tres, al costo de no cambiar nunca. `IOptionsSnapshot<T>` recalcula las opciones vinculadas una vez por scope (una vez por petición HTTP en ASP.NET Core) releyendo el `IConfiguration` actual, así que dentro de una misma petición todos los consumidores ven un valor consistente, y una petición posterior puede ver un valor más nuevo si la fuente subyacente se recargó; como es scoped, inyectarlo en un singleton es exactamente el error de captive dependency, y el contenedor de DI capturará un snapshot obsoleto para siempre, o lo rechazará si la validación está activada. `IOptionsMonitor<T>` se mantiene vivo a pesar de ser singleton: `CurrentValue` siempre refleja la configuración vinculada más reciente, y `OnChange` permite suscribirse para que te notifiquen cuando cambia, por lo que es el que se usa dentro de un `BackgroundService`, un singleton de vida larga, o en cualquier lugar donde se necesite reaccionar a una fuente recargable (un archivo JSON registrado con `reloadOnChange: true`, Azure App Configuration, refresco de Key Vault, etcétera). El trade-off es que `CurrentValue` puede cambiar entre dos lecturas dentro del mismo método, así que el código que necesita un valor internamente consistente para una operación debería leerlo una sola vez en una variable local en lugar de llamar a `CurrentValue` repetidamente.",
    rubric: [
      'Afirma que IOptions<T> se registra como singleton, se vincula la primera vez que se accede y nunca se vuelve a leer, y nunca refleja una recarga posterior',
      'Afirma que IOptionsSnapshot<T> es scoped, se recalcula una vez por scope/petición, y no se puede inyectar de forma segura en un singleton',
      'Afirma que IOptionsMonitor<T> es seguro para singletons y expone CurrentValue más OnChange para notificaciones de recarga en vivo',
      'Conecta IOptionsMonitor con BackgroundService/singletons de vida larga o con una fuente de configuración recargable como la razón para preferirlo ahí',
      'Menciona el riesgo de captive dependency al inyectar un tipo de opciones scoped en un singleton, o el riesgo de inconsistencia al releer CurrentValue durante una operación',
    ],
    explanation:
      "Esta pregunta revisa si \"el options pattern\" se entiende como tres lifetimes distintos que resuelven tres problemas distintos, y no como una sola API intercambiable. El detalle que más candidatos se pierden es que `IOptionsSnapshot<T>`, por ser scoped, es exactamente tan peligroso de inyectar en un singleton como cualquier otro servicio scoped — no es solo \"la versión con soporte de recarga\", y tampoco es la única excepción por ser segura en un singleton; `IOptions<T>` e `IOptionsMonitor<T>` también lo son.\n\n**Dilo en voz alta:** \"IOptions y IOptionsMonitor son ambos singletons, así que los dos son seguros en cualquier lado, incluidos otros singletons — IOptions se vincula una sola vez y nunca se vuelve a leer, Monitor se mantiene vivo mediante CurrentValue y OnChange. Snapshot es el scoped, así que es el que no puede ir en un singleton, aunque sea el que da la copia más consistente por petición.\"",
    hint:
      'Compara los tres por su propio ciclo de vida y por cuándo leen los valores enlazados; incluye qué pasa al inyectar el de scope en un singleton y cómo te llegan las notificaciones de cambio.',
  },
  'dotnet-dbcontext-thread-safety-tracking': {
    prompt:
      'Un `BackgroundService` inyecta un único `AppDbContext` en su constructor y lo retiene durante toda su vida, llamándolo de forma concurrente desde varios workers `Task.Run` para leer y actualizar filas. Lanza intermitentemente `InvalidOperationException: A second operation was started on this context before a previous operation completed`, y bajo carga algunas actualizaciones parecen desaparecer en silencio o aplicarse sobre datos obsoletos. ¿Qué está mal, y cómo lo rediseñarías?',
    modelAnswer:
      "`DbContext` — y la conexión y el change tracker que hay debajo — no es thread-safe: admite exactamente una operación en curso a la vez, y su protección de concurrencia es best-effort, así que una segunda llamada concurrente (incluso un `SELECT` compitiendo con otro `SELECT`) *puede* lanzar exactamente esa excepción, aunque no siempre lo haga, y las escrituras concurrentes que no activan esa protección igual pueden corromper o sobrescribir el estado rastreado de la otra. El síntoma de datos obsoletos tiene una segunda causa, separada de esa carrera: como un mismo `DbContext` se mantiene vivo durante toda la vida del `BackgroundService`, su change tracker hace resolución de identidad — una vez que una entidad con una clave determinada queda rastreada, una consulta posterior por esa misma clave devuelve la instancia ya rastreada en lugar de refrescarla desde la base de datos, así que un worker puede leer lo que parece ser el dato actual pero en realidad es una instantánea obsoleta cargada antes, y luego escribir una actualización calculada a partir de ella. El error real es un único `DbContext` de vida larga compartido durante toda la vida de un `BackgroundService` y entre tareas que corren de forma concurrente — la solución es dejar de compartirlo. Inyectaría `IDbContextFactory<AppDbContext>` (o `IServiceScopeFactory`) en lugar de `AppDbContext` directamente, y crearía un contexto de vida corta por unidad de trabajo — por mensaje de cola, por iteración del bucle, o por worker de `Task.Run` — usado solo para esa operación y descartado justo después, en lugar de un contexto que vive tanto como el servicio. Para las lecturas que no se van a modificar ni a guardar de vuelta a través de ese mismo contexto, agregaría `AsNoTracking()` para que el change tracker no tome una instantánea de entidades que nunca necesitará comparar, lo cual reduce memoria y CPU y evita recoger por accidente cambios rastreados que no vienen al caso. Si el job en segundo plano recorre muchas entidades y dispara una carga por fila, reemplazaría eso con una sola consulta con `Include` para un grafo que realmente se va a actualizar, o con una proyección (`Select` a un DTO) para un grafo de solo lectura, para evitar los round trips de N+1. Por último, cada lectura-modificación-`SaveChanges` por unidad de trabajo debería ser una sola unidad transaccional — la transacción implícita que `SaveChanges` abre por defecto suele bastar para una sola llamada, pero si el job necesita abarcar más de un `SaveChanges`, o si hay configurada una `SqlServerRetryingExecutionStrategy` resiliente, envolvería toda la unidad de trabajo en `strategy.ExecuteAsync` para que los reintentos repitan la operación completa en lugar de una parcial.",
    rubric: [
      'Identifica que DbContext y su change tracker no son thread-safe, y conecta eso directamente tanto con la excepción como con el síntoma de actualizaciones perdidas/obsoletas',
      'Propone crear un DbContext nuevo y de vida corta por unidad de trabajo mediante IDbContextFactory<T> o IServiceScopeFactory, en lugar de una instancia compartida durante toda la vida del BackgroundService y entre tareas concurrentes',
      'Menciona AsNoTracking para consultas de solo lectura, para reducir el costo del change tracker y evitar estado rastreado no deseado',
      'Menciona cómo evitar N+1 usando Include para grafos que se van a modificar o una proyección para grafos de solo lectura',
      'Aborda la corrección transaccional del SaveChanges por unidad de trabajo, incluyendo la advertencia sobre la execution strategy si hay reintentos configurados',
    ],
    explanation:
      "Este escenario junta a propósito varias facetas de nivel senior de EF Core en un solo reporte de bug realista: el texto de la excepción por sí solo cuenta la historia de concurrencia, pero el síntoma de \"las actualizaciones desaparecen en silencio\" es la parte que separa a quien simplemente envuelve la llamada en un lock de quien entiende que el change tracker, para empezar, no está pensado para compartirse así.\n\n**Dilo en voz alta:** \"DbContext y su change tracker no son thread-safe, así que un BackgroundService debería entregar un contexto nuevo y de vida corta por unidad de trabajo mediante IDbContextFactory o un scope, no compartir una sola instancia entre tareas concurrentes durante toda su vida.\"",
    hint:
      'Explica por qué `DbContext` no es thread-safe, qué le hace un change tracker de larga vida a la frescura de los datos y cómo obtener un contexto de vida corta por unidad de trabajo.',
  },
};
