// engine
import type { QuestionTranslation } from '../../engine/question';

export const translations: Record<string, QuestionTranslation> = {
  'spring-boot-application-annotation-basics': {
    prompt:
      "```java\n@SpringBootApplication\npublic class DemoApplication {\n    public static void main(String[] args) {\n        SpringApplication.run(DemoApplication.class, args);\n    }\n}\n```\n¿Qué combina la única anotación `@SpringBootApplication`?",
    options: {
      a: '`@Configuration` (marca la clase como fuente de definiciones de beans), `@EnableAutoConfiguration` (permite que Spring Boot configure beans según el classpath y cualquier propiedad que encuentre), y `@ComponentScan` (escanea el paquete de la clase anotada, y sus subpaquetes, en busca de componentes)',
      b: '`@Controller`, `@Service` y `@Repository` — agrupa las tres anotaciones de estereotipo para que cada clase del proyecto se trate automáticamente como las tres a la vez',
      c: 'Solo `@EnableAutoConfiguration`; `@Configuration` y `@ComponentScan` todavía hay que agregarlas por separado para que funcionen las definiciones de beans y el escaneo de componentes',
      d: '`@SpringBootTest`, `@ExtendWith(SpringExtension.class)` y `@AutoConfigureMockMvc` — arma un contexto de aplicación de pruebas para cada clase del proyecto',
    },
    explanation:
      '`@SpringBootApplication` está meta-anotada exactamente con estas tres: `@Configuration`, para que la clase también pueda declarar métodos `@Bean`; `@EnableAutoConfiguration`, para que Spring Boot inspeccione el classpath (y cualquier condición `@ConditionalOn...`) y configure beans como un Tomcat embebido o un `DataSource` sin XML; y `@ComponentScan` con raíz en el paquete de la clase anotada, para que las clases `@Component`/`@Service`/`@Repository`/`@Controller` debajo de ese paquete se descubran automáticamente. La opción b confunde las anotaciones de estereotipo (que marcan clases individuales para el escaneo) con lo que hace `@SpringBootApplication` en sí — no convierte retroactivamente a cada clase del proyecto en las tres cosas. La opción c es incorrecta porque `@Configuration` y `@ComponentScan` ya están incluidas; agregarlas de nuevo sería redundante, no necesario. La opción d confunde esto con anotaciones de testing, que son un asunto aparte, opcional, y solo para clases de prueba.',
  },
  'spring-boot-repository-interface-basics': {
    prompt:
      "```java\npublic interface ProductRepository extends JpaRepository<Product, Long> {\n    List<Product> findByNameContainingIgnoreCase(String name);\n}\n```\nNinguna clase del código implementa `ProductRepository`, y sin embargo se puede inyectar con `@Autowired` y usar para llamar a `.save(product)`, `.findById(id)` y `.findByNameContainingIgnoreCase(\"widget\")`. ¿Qué es `ProductRepository`, y de dónde sale su implementación?",
    options: {
      a: 'Es una interfaz de repositorio de Spring Data JPA. Al arrancar, Spring Data busca las interfaces que extienden `JpaRepository` (o similares) y crea un proxy en tiempo de ejecución que implementa los métodos CRUD heredados, además de derivar la consulta de `findByNameContainingIgnoreCase` a partir del propio nombre del método',
      b: 'Es una interfaz Java común; el compilador de Java 21 sintetiza automáticamente una implementación por defecto para cualquier interfaz cuyos nombres de método coincidan con nombres de campos de la clase entidad referenciada',
      c: 'Solo funciona porque `Product` implementa `Serializable`; Spring construye la implementación reflejando los getters y setters de `Product`, no la propia interfaz `ProductRepository`',
      d: 'La clase `@SpringBootApplication` debe declarar un método `@Bean` que devuelva `new ProductRepositoryImpl()`; el proxy se genera en tiempo de compilación mediante un procesador de anotaciones invocado desde ese método bean',
    },
    explanation:
      'Las interfaces de repositorio de Spring Data JPA no necesitan una implementación escrita a mano: al arrancar, la infraestructura de Spring Data encuentra cada interfaz que extiende alguna de sus interfaces base (`Repository`, `CrudRepository`, `JpaRepository`, etcétera) dentro de los paquetes escaneados y genera un proxy — respaldado por `SimpleJpaRepository` para los métodos heredados — que se registra como un bean de Spring bajo ese tipo de interfaz. Los métodos de consulta sin cuerpo, como `findByNameContainingIgnoreCase`, se resuelven analizando el nombre del método para construir una consulta JPQL en el arranque (`Containing` se vuelve un `LIKE %...%`, `IgnoreCase` envuelve ambos lados en una comparación sin distinguir mayúsculas); nada de esto depende de características del lenguaje de Java 21, y ningún compilador ni procesador de anotaciones genera una clase real `ProductRepositoryImpl`, lo cual descarta las opciones b y d. Que la entidad implemente `Serializable` no tiene relación con cómo se construye el proxy del repositorio, lo cual descarta la opción c.',
  },
  'spring-boot-circular-dependency-boot26': {
    prompt:
      "```java\n@Service\npublic class OrderService {\n    @Autowired\n    private PaymentService paymentService;\n}\n\n@Service\npublic class PaymentService {\n    @Autowired\n    private OrderService orderService;\n}\n```\nEste proyecto arranca sin problemas en Spring Boot 2.5. Después de actualizar a Spring Boot 3.x, el arranque falla con `BeanCurrentlyInCreationException`, reportando una referencia circular entre `orderService` y `paymentService`. ¿Qué cambió, y cuál es la solución recomendada (en lugar de simplemente silenciar la excepción)?",
    options: {
      a: 'Spring puede resolver una dependencia circular entre beans singleton inyectados por campo/setter exponiendo una referencia temprana, aún no completamente inicializada, de cada bean mientras el otro todavía se está construyendo — pero desde Spring Boot 2.6, `spring.main.allow-circular-references` es `false` por defecto, así que esa tolerancia está desactivada de forma predeterminada y el ciclo ahora falla de inmediato al arrancar. Volver a poner la propiedad en `true` silencia la excepción, pero no es la solución recomendada; la solución real es romper el ciclo — por ejemplo, inyectar uno de los dos lados de forma perezosa con `@Lazy`, extraer el comportamiento que ambos servicios necesitan a un tercer bean del que ninguno dependa, o rediseñar para que un servicio no necesite una referencia directa de vuelta al otro',
      b: 'Las dependencias circulares entre beans singleton nunca han sido resolubles por Spring en ninguna versión; el hecho de que esto arrancara en 2.5 significa que los beans nunca estuvieron realmente conectados entre sí, solo se registraba una advertencia de falso positivo',
      c: 'La excepción significa que `OrderService` y `PaymentService` deben anotarse ambos con `@Primary`; agregar `@Primary` a cualquiera de las dos clases resuelve la ambigüedad que dispara la verificación de referencia circular',
      d: 'Esto no tiene nada que ver con la versión de Spring Boot — ocurre porque las dos clases están anotadas `@Service` en lugar de que una fuera `@Component`; Spring solo permite un bean `@Service` por ciclo de dependencias',
    },
    explanation:
      "Las dependencias circulares inyectadas por campo/setter solían funcionar porque Spring instancia cada singleton con su constructor por defecto primero, guarda en caché una referencia temprana a esa instancia todavía no completamente poblada, y recién después realiza la inyección de campos/setters — así que `orderService` y `paymentService` pueden recibir cada uno una referencia a la instancia temprana del otro. (Los ciclos con inyección por constructor son otra historia y nunca han sido resolubles de esta manera, en ninguna versión de Spring, porque un constructor necesita sus argumentos antes de que el objeto exista siquiera). Spring Boot 2.6 cambió el valor por defecto de `spring.main.allow-circular-references` a `false`, así que el mismo ciclo por inyección de campo que funcionaba en silencio en 2.5 ahora falla de inmediato con `BeanCurrentlyInCreationException`. Volver a poner la propiedad en `true` restaura el comportamiento anterior, pero solo vuelve a ocultar un mal olor de diseño; la solución recomendada es eliminar el ciclo, lo más común con `@Lazy` en uno de los dos campos inyectados, para que ese lado solo se resuelva (a través de un proxy) la primera vez que realmente se use, bien después de que ambos beans terminen de construirse. Las opciones b, c y d están inventadas: la inyección circular por campo sí funcionaba antes de 2.6, `@Primary` resuelve *candidatos* ambiguos para un solo punto de inyección y no tiene relación con los ciclos, y Spring no impone ningún límite de ese tipo sobre cuántos beans `@Service` pueden aparecer en un grafo de dependencias.",
  },
  'spring-boot-valid-requestbody-response': {
    prompt:
      "```java\n@RestController\n@RequestMapping(\"/api/orders\")\npublic class OrderController {\n\n    @PostMapping\n    public ResponseEntity<OrderResponse> create(@Valid @RequestBody CreateOrderRequest request) {\n        Order saved = orderService.create(request);\n        return ResponseEntity.status(HttpStatus.CREATED).body(OrderResponse.from(saved));\n    }\n\n    @GetMapping(\"/{id}\")\n    public ResponseEntity<OrderResponse> getById(@PathVariable Long id,\n                                                  @RequestParam(required = false) Boolean includeItems) {\n        // ...\n    }\n}\n```\n¿Cuáles afirmaciones sobre este controlador son correctas? Selecciona todas las que apliquen.",
    options: {
      a: '`@RequestBody` deserializa el cuerpo de la petición JSON en una instancia de `CreateOrderRequest` usando un `HttpMessageConverter` registrado (Jackson por defecto); `@Valid` luego ejecuta las restricciones de Bean Validation declaradas en los campos de `CreateOrderRequest`, y una restricción que falla hace que Spring MVC rechace la petición con una respuesta de nivel 400 antes de que se ejecute el cuerpo de `create`',
      b: '`@PathVariable Long id` vincula el segmento `{id}` de la plantilla de URL al parámetro `id`, mientras que `@RequestParam(required = false) Boolean includeItems` vincula un parámetro opcional de query string (por ejemplo, `?includeItems=true`); una petición que omite `includeItems` lo deja en `null` en lugar de fallar',
      c: 'Devolver `ResponseEntity<OrderResponse>` en lugar de un `OrderResponse` simple es obligatorio para que funcione la serialización JSON — si `create` devolviera en cambio un `OrderResponse` simple, `@RestController` no tendría forma de escribirlo en el cuerpo de la respuesta',
      d: '`@RestController` es la forma abreviada de `@Controller` combinado con `@ResponseBody` aplicado a cada método manejador, así que los valores de retorno se escriben directamente en el cuerpo de la respuesta HTTP mediante conversión de mensajes en lugar de resolverse como el nombre de una vista',
      e: 'Si `CreateOrderRequest` no tiene ninguna anotación de restricción de Bean Validation en ningún campo (sin `@NotNull`, `@Size`, etc.), poner `@Valid` delante de `@RequestBody` hace que la aplicación no arranque, porque no hay nada que el validador pueda revisar',
    },
    explanation:
      "a y b describen el comportamiento estándar y bien definido de `@RequestBody`/`@Valid` y `@PathVariable`/`@RequestParam`, y son correctas tal como están escritas. d también es correcta: `@RestController` es exactamente `@Controller` + `@ResponseBody`, por eso los métodos manejadores devuelven datos en lugar de un nombre de vista. c es falsa — `@RestController` aplica `@ResponseBody` a cada manejador sin importar el tipo de retorno, así que un `OrderResponse` simple se serializa a JSON con un `200 OK` por defecto sin problema; `ResponseEntity` solo hace falta cuando el método quiere controlar el código de estado, los encabezados, o ambos, de forma explícita (como hace `create` aquí para devolver `201 Created`), no para que la serialización sea posible. e es falsa — `@Valid` sin restricciones en el tipo destino es un no-op inofensivo: la validación se ejecuta, no encuentra nada que revisar, y la petición sigue adelante; no provoca ni un fallo de arranque ni un error en tiempo de ejecución.",
  },
  'spring-boot-save-vs-merge': {
    prompt:
      "```java\npublic interface ProductRepository extends JpaRepository<Product, Long> {}\n\n@Service\npublic class ProductService {\n    private final ProductRepository repository;\n    // constructor omitido\n\n    public Product createOrUpdate(Product product) {\n        return repository.save(product);\n    }\n}\n```\n`Product.id` está anotado `@Id @GeneratedValue(strategy = GenerationType.IDENTITY)`. Un llamador construye `new Product()`, dejando `id` en `null`, y llama a `createOrUpdate`. ¿Qué hace `JpaRepository.save(...)` en ese caso — y en qué se diferenciaría el comportamiento si el llamador en cambio pasara un `Product` con un `id` no nulo que todavía no existe en la base de datos (digamos, un id copiado de otro sistema)?",
    options: {
      a: '`SimpleJpaRepository.save` decide entre insertar y actualizar comprobando si la entidad es "nueva" — para un id `@GeneratedValue`, esa comprobación es simplemente `id == null`. Con `id == null`, Hibernate realiza un `INSERT` mediante `persist`, y la clave generada se escribe de vuelta en `product`. Con un `id` no nulo que todavía no está en la base de datos, la misma comprobación ahora trata a la entidad como **no nueva**, así que `save` llama a `merge` en su lugar: Hibernate primero emite un `SELECT` para buscar esa fila, no encuentra nada, y de todas formas termina insertándola — pero por el camino, más costoso, de merge/select en lugar de un `persist` directo',
      b: '`save` siempre realiza un `INSERT` sin importar el valor de `id`; si ya existe una fila con ese `id`, la base de datos lo rechaza con una violación de clave primaria, así que `save` nunca puede usarse para actualizar una fila existente — hay que agregar un método `update` aparte al repositorio para eso',
      c: 'Si `save` inserta o actualiza depende únicamente de si la transacción que lo rodea es `@Transactional(readOnly = true)`: una transacción de solo lectura siempre resulta en `merge`, una transacción de escritura siempre resulta en `persist`, sin importar el valor de `id`',
      d: 'Como `Product` usa `GenerationType.IDENTITY`, Hibernate solo puede asignar el id después de insertar la fila, así que llamar a `save` con un `id` no nulo, aún no persistido, lanza `IdentifierGenerationException` de inmediato, antes de enviar cualquier SQL',
    },
    explanation:
      "Este es un problema bien conocido porque ambos caminos terminan insertando la fila, así que la diferencia es fácil de pasar por alto en una prueba rápida, pero se manifiesta como `SELECT`s extra (o como comportamiento sorprendente en entidades que implementan `Persistable` y sobrescriben `isNew()`) bajo carga. La opción b es incorrecta — `save` es el punto de entrada combinado de Spring Data para crear-o-actualizar precisamente para que los llamadores no necesiten un método `update` aparte; enruta a `persist` o `merge` según la comprobación de nuevo/no-nuevo, no siempre a `INSERT`. La opción c está inventada — `readOnly` solo afecta cómo se configura la transacción (por ejemplo, una pista para omitir el dirty checking y, en algunos drivers, marcar la conexión como de solo lectura); no participa en la decisión de persist-vs-merge. La opción d es incorrecta — Hibernate no rechaza un id no nulo de entrada; usa el valor no nulo del id para decidir que la entidad 'no es nueva' y sigue el camino de merge descrito en la opción a en lugar de lanzar una excepción.",
  },
  'spring-boot-transactional-self-invocation': {
    prompt:
      "```java\n@Service\npublic class ReportService {\n\n    public void generateMonthlyReport() {\n        // ... construir el reporte ...\n        saveReport();\n    }\n\n    @Transactional\n    public void saveReport() {\n        reportRepository.save(report);\n        auditRepository.save(audit);\n    }\n}\n```\nUn llamador inyecta `ReportService` y llama a `generateMonthlyReport()`. Ambas escrituras de repositorio dentro de `saveReport()` se ejecutan, pero en realidad no corren dentro de una transacción — si `auditRepository.save(audit)` lanza una excepción, `reportRepository.save(report)` no se revierte. ¿Por qué `@Transactional` no hace nada en silencio aquí, y cómo reestructurarías el código para arreglarlo?",
    modelAnswer:
      "Por defecto, Spring implementa `@Transactional` (y `@Cacheable`, `@Async`) con AOP basado en proxies: para un bean basado en clase como este (sin interfaz), Spring crea al arrancar una subclase CGLIB de `ReportService` y registra *ese proxy* como el bean que se inyecta en otros componentes. El proxy sobrescribe `saveReport()` para abrir una transacción, invocar el método real en el objeto de destino subyacente, y confirmar o revertir alrededor de él. Esa interceptación solo ocurre para llamadas que llegan *a través de la referencia al proxy*. Dentro de `generateMonthlyReport()`, la llamada `saveReport()` es en realidad `this.saveReport()` — una llamada virtual de Java normal sobre el objeto de destino sin envolver, hecha desde código que ya está corriendo dentro del propio destino (el proxy ya delegó hacia él para ejecutar `generateMonthlyReport()`). Esa llamada nunca vuelve a salir a través del proxy, así que el advice transaccional alrededor de `saveReport()` nunca se dispara, y ambos guardados corren fuera de cualquier transacción, de forma no atómica. La misma regla se aplica de forma idéntica a `@Cacheable` y `@Async` en un método auto-invocado, y los proxies estándar de Spring AOP solo pueden interceptar métodos públicos llamados desde fuera de la clase — un método privado nunca puede recibir advice, sea con proxy o no, porque el proxy tiene que sobrescribir o implementar el método para interceptarlo. Para arreglarlo, hay que enrutar la llamada a través del proxy en lugar de a través de `this`: la opción más limpia es mover `saveReport()` a su propio bean colaborador y hacer que `ReportService` llame a ese bean; alternativamente, inyectar una autorreferencia (`@Lazy @Autowired private ReportService self;`) y llamar a `self.saveReport()`, o habilitar `@EnableAspectJAutoProxy(exposeProxy = true)` y llamar a `((ReportService) AopContext.currentProxy()).saveReport()`. Extraer un bean colaborador suele ser preferible porque no depende de detalles internos del proxy y mantiene honesta la API pública de la clase sobre qué es transaccional.",
    rubric: [
      'Identifica que @Transactional (como @Cacheable y @Async) se implementa envolviendo el bean en un proxy (una subclase CGLIB aquí, al no haber interfaz), no reescribiendo la clase misma',
      'Establece que llamar a saveReport() como this.saveReport() desde dentro de la misma clase es una auto-invocación que evita el proxy por completo, así que no se ejecuta ningún advice transaccional',
      'Da al menos una solución concreta que enrute la llamada de vuelta a través del proxy: un bean colaborador aparte, una autorreferencia inyectada, o AopContext.currentProxy() con exposeProxy habilitado',
      'Señala que solo los métodos públicos llamados desde fuera de la clase (a través de una referencia inyectada/del proxy) pueden recibir advice — un método privado nunca puede recibirlo de esta forma',
    ],
    explanation:
      "Este es el problema con `@Transactional` más común en código real, y casi nunca se anuncia como una pregunta sobre proxies — aparece como \"¿por qué no se revirtió esto?\" días después de que el código se escribió y se revisó. La trampa para quienes saben que `@Transactional` existe pero no cómo se implementa es asumir que las anotaciones actúan sobre el método sin importar desde dónde se llame, en lugar de actuar solo sobre las llamadas que cruzan el límite del proxy.\n\n**Dilo en voz alta:** \"`@Transactional` solo se dispara en llamadas que pasan por el proxy del bean, así que llamar a `saveReport()` como `this.saveReport()` desde dentro de la misma clase lo evita por completo; movería ese método a otro bean o inyectaría una autorreferencia para que la llamada vuelva a salir por el proxy.\"",
  },
  'spring-boot-controlleradvice-problemdetail': {
    prompt:
      "```java\n@RestControllerAdvice\npublic class ApiExceptionHandler {\n\n    @ExceptionHandler(ProductNotFoundException.class)\n    public ProblemDetail handleNotFound(ProductNotFoundException ex) {\n        ProblemDetail problem = ProblemDetail.forStatusAndDetail(HttpStatus.NOT_FOUND, ex.getMessage());\n        problem.setProperty(\"productId\", ex.getProductId());\n        return problem;\n    }\n}\n```\nSpring Framework 6 agregó soporte de primera clase para `ProblemDetail` (RFC 7807/9457). ¿Qué afirmación describe mejor lo que logra este manejador comparado con construir a mano un DTO de error propio?",
    options: {
      a: '`ProblemDetail` es una representación integrada del formato "problem+json", con los campos estándar (`type`, `title`, `status`, `detail`, `instance`) más miembros de extensión arbitrarios mediante `setProperty`; devolverlo desde un `@ExceptionHandler` hace que Spring MVC lo serialice como `application/problem+json`, tomando el estado HTTP del propio objeto, dándole a cada endpoint una forma de error consistente y basada en un estándar en lugar de un DTO propio por equipo',
      b: '`ProblemDetail` reemplaza a `@ExceptionHandler` por completo: anotar una clase con `@RestControllerAdvice` sin ningún método `@ExceptionHandler` convierte automáticamente cada excepción no capturada de la aplicación en una respuesta RFC 7807',
      c: 'Devolver un `ProblemDetail` desde este método hace que Spring revierta automáticamente cualquier transacción de base de datos abierta, algo que un DTO de error escrito a mano no haría, porque `ProblemDetail` participa en la sincronización de transacciones',
      d: '`ProblemDetail` solo funciona cuando el tipo de retorno del método manejador es `ResponseEntity<ProblemDetail>`; devolver un `ProblemDetail` desnudo, como hace este método, es ignorado por Spring MVC y el cliente recibe un `200 OK` vacío',
    },
    explanation:
      "`ProblemDetail` estandariza lo que antes era un DTO de error improvisado por aplicación: modela directamente los campos de RFC 7807/9457, `setProperty` cubre extensiones específicas del dominio como `productId`, y Spring MVC tiene soporte dedicado tanto para serializarlo como `application/problem+json` como para derivar el estado HTTP de la respuesta a partir de `ProblemDetail.getStatus()` cuando el método devuelve un `ProblemDetail` desnudo en lugar de un `ResponseEntity` — justo por eso la opción d es incorrecta; envolverlo en `ResponseEntity` solo hace falta cuando hay que fijar encabezados adicionales, no para que funcionen el estado o el cuerpo. La opción b exagera: los métodos `@ExceptionHandler` (o las sobrescrituras de `ResponseEntityExceptionHandler`) igual hay que escribirlos para capturar tipos de excepción específicos y construir el `ProblemDetail`; nada los genera automáticamente a partir de una clase de advice vacía. La opción c está inventada — `ProblemDetail` es un simple portador de datos sin relación con la sincronización de transacciones; cualquier reversión sigue dependiendo de las reglas normales de rollback de `@Transactional` para la excepción que se lanzó.\n\n**Dilo en voz alta:** \"`ProblemDetail` es la forma de error RFC 7807 integrada en Spring, y devolverlo desnudo desde un `@ExceptionHandler` alcanza — Spring MVC lee el estado del propio objeto y lo serializa como `application/problem+json` sin necesitar envolverlo en `ResponseEntity`.\"",
  },
  'spring-boot-n-plus-one-lazy-loading': {
    prompt:
      "```java\n@Entity\npublic class Author {\n    @Id @GeneratedValue\n    private Long id;\n    private String name;\n\n    @OneToMany(mappedBy = \"author\")\n    private List<Book> books;\n}\n\n@Transactional(readOnly = true)\npublic List<AuthorSummary> listAuthorsWithBookCount() {\n    List<Author> authors = authorRepository.findAll();\n    return authors.stream()\n        .map(a -> new AuthorSummary(a.getName(), a.getBooks().size()))\n        .toList();\n}\n```\nCon 200 autores, este método dispara 201 sentencias SQL, y — si la colección se accediera en cambio fuera de una transacción, o con `spring.jpa.open-in-view=false` y ninguna sesión activa en el momento en que corre `.getBooks()` — podría lanzar `LazyInitializationException` en su lugar. Explica ambos problemas y cómo arreglarías cada uno.",
    modelAnswer:
      "Las 201 consultas son un N+1 clásico: `authorRepository.findAll()` emite un único `SELECT` para los autores, y `@OneToMany` usa `FetchType.LAZY` por defecto, así que `books` queda como un proxy/colección sin inicializar en cada `Author`. La primera vez que `a.getBooks()` se ejecuta dentro del stream, Hibernate dispara un `SELECT ... WHERE author_id = ?` aparte para los libros de ese autor — una consulta extra por autor, así que 1 + 200 = 201 en total, creciendo de forma lineal con la cantidad de autores. La solución es dejar de cargar los libros de a uno por autor: agregar `JOIN FETCH` a un finder JPQL (`SELECT a FROM Author a LEFT JOIN FETCH a.books`), o anotar el método del repositorio con `@EntityGraph(attributePaths = \"books\")`, cualquiera de los dos convierte esto en un único join SQL en lugar de N selects adicionales. Para este caso de uso en particular — donde solo hace falta el *conteo* de libros, no los libros en sí — una solución todavía mejor es no cargar las entidades `Book` en absoluto y en cambio consultar una proyección con `COUNT(b) GROUP BY a.id` (o un método derivado/`@Query` que devuelva `Map<Long, Long>` o un DTO), lo cual evita traer a memoria filas de libros potencialmente grandes solo para llamar a `.size()`.\n\n`LazyInitializationException` es un problema aparte, aunque relacionado: un proxy o colección lazy necesita una sesión de Hibernate abierta (el contexto de persistencia activo) para ejecutar su consulta de carga diferida la primera vez que se toca. Si `.getBooks()` se llama después de que el método `@Transactional` ya retornó y su sesión se cerró — o con `open-in-view` deshabilitado en Spring Boot y ninguna transacción activa en absoluto — no queda ninguna sesión para ejecutar esa consulta, y Hibernate lanza una excepción en lugar de cargarla en silencio. El valor por defecto de Spring Boot, `spring.jpa.open-in-view=true`, evita este síntoma manteniendo la sesión de Hibernate abierta durante toda la petición HTTP (incluyendo el renderizado de la vista), así que el acceso lazy en cualquier punto de la pila de llamadas tiene éxito en silencio — pero lo logra ocultando consultas N+1 como esta fuera del límite visible de `@Transactional`, manteniendo una conexión de base de datos reservada más tiempo del necesario, y dificultando saber cuándo se ejecutan realmente las consultas con solo leer la capa de servicio. La solución recomendada es deshabilitar `open-in-view` explícitamente y asegurarse de que cada asociación que un caso de uso realmente necesita se cargue dentro del propio método `@Transactional` — mediante `JOIN FETCH`/`@EntityGraph` o un acceso explícito antes de que el método retorne — para que el límite de la transacción y el límite de la consulta sean el mismo límite.",
    rubric: [
      'Identifica la causa del N+1: @OneToMany usa LAZY por defecto, así que cada llamada a a.getBooks() en el bucle dispara su propio SELECT, dando 1+N consultas en total',
      'Propone JOIN FETCH o @EntityGraph como la solución que colapsa el N+1 en una sola consulta, e idealmente también menciona una proyección COUNT/GROUP BY para un caso de solo conteo como este',
      'Explica LazyInitializationException como un proxy/colección lazy que necesita una sesión de Hibernate abierta que ya no está disponible en el momento en que se accede',
      'Explica qué hace open-in-view (mantiene la sesión abierta durante toda la petición) y que oculta el N+1 en lugar de arreglarlo, al costo de consultas ocultas y una conexión reservada por más tiempo',
      'Recomienda deshabilitar open-in-view y cargar dentro del propio método @Transactional todo lo que un caso de uso necesita',
    ],
    explanation:
      "Este escenario combina a propósito dos hechos relacionados pero distintos de nivel senior: el N+1 es un bug de rendimiento que igual funciona, mientras que `LazyInitializationException` es un bug de corrección que falla de forma ruidosa — y `open-in-view` queda en el medio, convirtiendo el segundo en una versión silenciosa y costosa del primero en lugar de arreglarlo de verdad.\n\n**Dilo en voz alta:** \"Las 201 consultas son N+1 por el `@OneToMany` lazy que se toca por autor dentro de un bucle, y se arregla con `JOIN FETCH` o `@EntityGraph`; `open-in-view` solo oculta `LazyInitializationException` manteniendo la sesión abierta durante toda la petición, así que lo desactivaría y cargaría lo que necesito dentro de la transacción.\"",
  },
};
